[tool.poetry]
name = "qhbayes"
version = "0.0.11"
description = "Bayesian methods for inferring mass eruption rate for column height (or vice versa) for volcanic eruptions"
authors = ["markwoodhouse <mark.woodhouse@bristol.ac.uk>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8,<3.11"
setuptools = "^60.10.0"
argparse = "^1.4.0"
matplotlib = "^3.5.1"
Pint = "^0.18"
numpy = ">=1.15.0,<1.22.2"
pandas = "^1.4.1"
scipy = ">=1.7.3,<1.8.0"
seaborn = "^0.11.2"
arviz = "^0.11.4"
pymc3 = "^3.11.5"
dash = "^2.3.0"
dash-bootstrap-components = "^1.0.3"
plotly = "^5.6.0"
dash-extensions = "^0.0.71"
odfpy = "^1.4.1"
openpyxl = "^3.0.9"
click = "<8,>=4.0"

[tool.poetry.plugins] # Optional super table

[tool.poetry.scripts]
QHBayes_Example = "qhbayes.scripts.example:run_example"
QHBayes_App = "qhbayes.scripts.run_app:run_app"
QHBayes = "qhbayes.scripts.run_qhbayes:run_qhbayes"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
