[tool.poetry]
name = "labctrl"
version = "0.2.2"
description = "A unified framework for controlling programmable lab instruments"
authors = ["Atharv Joshi <atharvjoshi@ymail.com>"]

[tool.poetry.dependencies]
python = ">=3.9,<3.11"
numpy = "^1.21.3"
PyYAML = "^6.0"
PyVISA = "^1.11.3"
PyVISA-py = "^0.5.2"
PySide6 = "^6.2.3"
loguru = "^0.6.0"
Pyro5 = "^5.13.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
Sphinx = "^4.2.0"
black = "^21.9b0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
