[tool.poetry]
name = "char-picture"
version = "0.1.0"
description = ""
authors = ["winfred_wu <869286203@qq.com>"]

[tool.poetry.dependencies]
python = "^3.10"
cowpy = "^1.1.5"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[[tool.poetry.source]]
name = "douban"
url = "https://pypi.doubanio.com/simple"