
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-06T22:44:57+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "fe50b5ca4580a0210343bfcee559831888e80a87",
 "version": "7.3.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
