
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-04T14:19:35+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "c56e1bf1891df5cd5159e2224a7ad6c155662704",
 "version": "0.4.132"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
