
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-07T15:29:45+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "3d5d5c8f9c973f13d591803d6904eebcfc5566fd",
 "version": "1.4.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
