[tool.poetry]
name = "{{model_name}}"
version = "0.1.0"
description = ""
authors = ["{{name}} <{{email}}>"]

[tool.poetry.dependencies]
python = "^3.9"
Flask = "^2.0.3"
gunicorn = "20.1.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
