[tool.poetry]
name = "wi_voice_main"
version = "0.1.0"
description = "Easy voice"
authors = ["Willis"]

[tool.poetry.dependencies]
python = "^3.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
