[build-system]
requires = ["setuptools", "wheel"]

[tool.black]
line-length = 88

[tool.isort]
profile = "black"
combine_as_imports = true

[tool.mypy]
python_version = "3.8"
show_error_codes = true
warn_unused_configs = true
warn_unused_ignores = true
warn_unreachable = true
show_error_context = true
disallow_untyped_defs = false  # TODO: add missing annotations and switch this option to true

# TODO: switch off when upstream is correctly typed
# see https://github.com/matplotlib/matplotlib/issues/20504
ignore_missing_imports = true
