[tool.poetry]
name = "file_binary"
version = "0.6.0"
description = "File Binary is a package with some tools to help you with binary files"
authors = ["matheus <geof.matheus@gmail.com>"]

repository = 'https://github.com/MatheusRamo/file_binary'
readme = 'README.md'
keywords = ['text']

[tool.poetry.dependencies]
python = "^3.9"
numpy = "^1.22.3"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
