# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tracdap/config/common.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1btracdap/config/common.proto\x12\x0etracdap.config*H\n\x0c\x43onfigFormat\x12\x19\n\x15\x43ONFIG_FORMAT_NOT_SET\x10\x00\x12\x08\n\x04YAML\x10\x01\x12\x08\n\x04JSON\x10\x02\x12\t\n\x05PROTO\x10\x03\x42\x1c\n\x18org.finos.tracdap.configP\x01\x62\x06proto3')

_CONFIGFORMAT = DESCRIPTOR.enum_types_by_name['ConfigFormat']
ConfigFormat = enum_type_wrapper.EnumTypeWrapper(_CONFIGFORMAT)
CONFIG_FORMAT_NOT_SET = 0
YAML = 1
JSON = 2
PROTO = 3


if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\030org.finos.tracdap.configP\001'
  _CONFIGFORMAT._serialized_start=47
  _CONFIGFORMAT._serialized_end=119
# @@protoc_insertion_point(module_scope)
