
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-06T18:55:14-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "6b3027de1cc949c89b31b8dd979b4898da2d9ce8",
 "version": "5.8.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
