
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-04T18:20:42+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "ac18cadf78040a68408b222fe50bc9d953a2ba98",
 "version": "0.38.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
