[tool.poetry]
name = "directbank"
version = "0.0.1"
description = ""
authors = ["Toony <kizyanov@protonmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
xsdata = "^22.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
