[tool.poetry]
name = "gaussianprocessderivatives"
version = "0.1.5"
description = "Uses Gaussian processes to smooth data and estimate first- and second-order derivatives"
authors = ["Peter Swain"]
license = "MIT"
readme = "projectdescription.txt"
keywords = ["gaussian process", "derivative"]
classifiers= [
  "Topic :: Scientific/Engineering",
  "Operating System :: OS Independent",
  "Intended Audience :: Science/Research",
]

[tool.poetry.dependencies]
python = "^3.6.0,<3.11"
scipy = "^1.7.3"
matplotlib = "^3.5.1"
numpy = "^1.16.0"


[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
