# -*- coding: utf-8 -*-

"""
firstlanguage

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""

import unittest

from firstlanguage_python.configuration import Configuration
from firstlanguage_python.configuration import Environment
from firstlanguage_python.firstlanguage_client import Client


class ControllerTestBase(unittest.TestCase):

    """All test classes inherit from this base class. It abstracts out
    common functionality and configuration variables set up."""

    @classmethod
    def setUpClass(cls):
        """Class method called once before running tests in a test class."""
        cls.request_timeout = 30
        cls.assert_precision = 0.01
        cls.config = ControllerTestBase.create_configuration()
        cls.client = Client()
        cls.auth_managers = cls.client.auth_managers
    @staticmethod
    def create_configuration():
        return Configuration()

if __name__ == '__main__':
    unittest.main()