[tool.poetry]
name = "nonebot-plugin-htmlrender"
version = "0.0.4.6"
description = "通过浏览器渲染图片"
authors = ["kexue <xana278@foxmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.7.3,<4.0"
playwright = "^1.17.2"
nonebot2 = "^2.0.0-beta.1"
nonebot-adapter-onebot = "^2.0.0-beta.1"
jinja2 = "^3.0.3"
markdown = "^3.3.6"
Pygments = "^2.10.0"
python-markdown-math = "^0.8"
pymdown-extensions = "^9.1"
aiofiles = "^0.8.0"
uvicorn = "^0.17.6"


[tool.poetry.dev-dependencies]
black = "^21.12b0"
pillow = "^8"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[[tool.poetry.source]]
name = "aliyun"
url = "https://mirrors.aliyun.com/pypi/simple/"
default = true