[tool.poetry]
name = "test-poetrino"
version = "0.1.6"
description = ""
authors = ["Sasen Perera <sasen.learnings@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
blessed = "^1.19.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
