[tool.poetry]
name = "csdatatools"
version = "0.1.0-alpha.2"
description = "Children's Services Data Tools - Utilities for cleaning and normalising CS data by Social Finance"
authors = [
    "Michael Hanks <michael.hanks@socialfinance.org.uk>",
    "Patrick Troy <patrick.troy@socialfinance.org.uk>",
    "Céline Gross <celine.m.gross@gmail.com>",
    "Kaj Siebert <kaj@k-si.com>"
]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
lxml = "^4.8.0"
more-itertools = "^8.12.0"
sfdata-stream-parser = "0.4.0"
xmlschema = "^1.10.0"
click = "^8.1.2"
PyYAML = "^6.0"
tablib = {extras = ["cli", "xlsx"], version = "^3.2.0"}

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
