
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-01T23:23:58+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "f9411c3bbec810229f99e0ed9833dc7beca3e523",
 "version": "0.0.71.post0.dev118"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
