[build-system]
requires = ["flit_core ~=3.2"]
build-backend = "flit_core.buildapi"

[project]
name = "boost-game"
authors = [{name = "Aaron Friesen", email = "maugrift@maugrift.com"}]
readme = "README.md"
license = {file = "LICENSE.txt"}
classifiers = ["License :: OSI Approved :: GNU Affero General Public License v3 or later (AGPLv3+)"]
dynamic = ["version", "description"]
dependencies = [
	"discord.py ~=1.7.3",
	"termcolor ~=1.1.0",
]

[project.urls]
Home = "https://github.com/Maugrift/boost"

[project.scripts]
boost = "boost_game.boost:main"

[tool.flit.module]
name = "boost_game"
