
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-01T15:01:35+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "f9cc5ea89e0336f5aac75e0726793dfa9393229d",
 "version": "2.10.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
