[tool.poetry]
name = "waterservices"
version = "0.1.0"
description = ""
authors = ["javad-rzvn <javad.rezvanpour@gmail.com>"]
repository = "https://github.com/javad-rzvn/waterservices"


[tool.poetry.dependencies]
python = "^3.7"
pandas="^1.3.5"
dask="^2022.2.0"
tqdm="^4.64.0"
requests="^2.27.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
