[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "dreamtim"
authors = [{name = "Timofei Ryko", email = "timofei.ryko@gmail.com"},]
license = {file = "LICENSE"}
classifiers = ["License :: OSI Approved :: MIT License"]
dynamic = ["version", "description"]
readme = "README.md"
requires-python = ">=3.6"

[project.urls]
Home = "https://github.com/dreamtim1/dreamtim"
