
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-07T00:23:29-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "8134ce38b5fa49903013e9e6cb7c8c31f5ffec03",
 "version": "0.22.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
