
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-05T11:20:51+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "bcee99f64c2465f4e3dcb33e87732ff23fd0071c",
 "version": "0.7.1.post.dev501"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
