
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-06T15:14:02-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "5edb3a4bad6c1c3de2bb560c1469c7e581c11710",
 "version": "1.15.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
