[tool.poetry]
name = "spicypy"
version = "0.1.0"
description = "A python package for signal processing & control systems. Combining several tools to facilitate signal processing, control systems modelling, and the interface between the two."
authors = ["Artem Basalaev <artem.basalaev@physikDOTuni-hamburg.de>", "Christian Darsow-Fromm <cdarsowf@physnetDOTuni-hamburg.de>", "Martin Hewitson <martin.hewitson@aeiDOTmpg.de>", "Oliver Gerberding <oliver.gerberding@physikDOTuni-hamburg.de>"]
repository = "https://gitlab.com/pyda-group/spicypy"
documentation = "https://gitlab.com/pyda-group/spicypy/-/blob/master/README.md"

[tool.poetry.dependencies]
python = ">=3.7.1,<3.11"
scipy = ">=1.5,<2.0"
numpy = ">=1.18,<2.0"
importlib-metadata = {version = "^1.1.3", python = "<=3.7"}
matplotlib = ">=3.0,<4.0"
h5py = ">=3,<4"
lpsd = ">=0.2,<0.3"

[tool.poetry.dev-dependencies]
black = "^22.1"
pytest = "^6.2.5"
pytest-cov = "^3.0.0"
pre-commit = "^2.15.0"
mypy = "^0.931"
pylint = "^2.12.1"
isort = "^5.10.1"
seed-isort-config = "^2.2.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "--verbose -x --log-level=INFO --cov pyda --cov-report term-missing --no-cov-on-fail --cov-report=html --cov-report=xml"
testpaths = [
    "tests",
]

[tool.coverage]
    [tool.coverage.run]
    omit =[]
    [tool.coverage.report]
    fail_under = 54
    omit =[]

    [tool.coverage.html]
    directory = "htmlcov"

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 88
