[project]
authors = [
    {name = "Benoît Crabbé", email = "benoit.crabbe@univ-paris-diderot.fr"},
    {name = "Loïc Grobol", email = "lgrobol@parisnanterre.fr"},
]
dependencies = [
    "bidict",
    "boltons",
    "click >= 8.0.4, < 9.0.0",
    "fastapi",
    "fasttext ~= 0.9",
    "loguru",
    "protobuf",
    "pydantic",
    "pyyaml",
    "rich",
    "sentencepiece",
    "torch >= 1.8.1, < 1.12.0, != 1.10.0",
    "transformers >= 4.12.2, < 5.0.0",
    "uvicorn",
]
keywords = [
    "nlp",
    "parsing",
]
license = {text = "MIT"}
name = "hopsparser"
readme = "README.md"
requires-python = ">=3.8"
urls = {repository = "https://github.com/hopsparser/hopsparser"}
version = "0.4.2"

[options.optional_dependencies]
traintools = ["pandas"]
tests = [
    "hypothesis",
    "pytest",
    "pytest-assert-utils",
    "pytest-console-scripts",
    "pytest-lazy-fixture",
]

[project.scripts]
hopsparser = "hopsparser.main:cli"
eval_parse = "hopsparser.conll2018_eval:main"

[build-system]
requires = ["setuptools>=54", "wheel"]
build-backend = "setuptools.build_meta"

[tool.isort]
profile = "black"
multi_line_output = 3