
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-03T02:34:32+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "563319a8ee2d0ba87815f879b533a169fcc36c84",
 "version": "0.9.dev2214"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
