[tool]
[tool.poetry]
name = "ppwjb"
version = "0.0.3"
description = "Python project wizard with Jupyter Book"
license = "BSD-3-Clause"
authors = ["Ondra Zahradnik <ondra.zahradnik@gmail.com>"]
readme = "README.md"
repository = "https://github.com/ondraz/cookiecutter-pypackage-jupyter-book"
documentation = "https://ondraz.github.io/cookiecutter-pypackage-jupyter-book/"
keywords = ['cookiecutter', 'template', 'package']
packages = [
  {include = "ppwjb"}
]

include = [
  '{{cookiecutter.project_slug}}/**/*',
  'cookiecutter.json',
  'hooks/*'
]

[tool.poetry.dependencies]
python = ">=3.7,<3.11"
cookiecutter = "1.7.2"

pytest = {version = "^5.4.3", optional=true}
pytest-cookies = {version = "^0.5.1", optional=true}
pyyaml = {version="^5.3.1",optional=true}
pytest-cov = {version="^2.10.1",optional=true}
tox = {version = "^3.20.1", optional=true}
fire = {version="^0.4.0", optional=true}
jupyter-book = "^0.12.2"

[tool.poetry.extras]
dev = [
  "pytest",
  "pytest-cookies",
  "pyyaml",
  "pytest-cov",
  "tox",
  "fire",
  "jupyter-book"
]

[tool.black]
line-length = 120
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | book
)/
'''

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
ppwjb = 'ppwjb.cli:main'
