
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-01T18:01:22-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "b3ca20e6765c7cff2d5b095e880dc2b2a811d825",
 "version": "0.18.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
