[tool.poetry]
name = "powershap"
version = "0.0.2"
description = "Feature selection using statistical significance of shap values"
authors = ["Jarne Verhaeghe, Jeroen Van Der Donckt"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.8,<3.11"
numpy = "^1.22.3"
pandas = "^1.4.1"
shap = "^0.40.0"
sklearn = "^0.0"
catboost = "^1.0.5"

[tool.poetry.dev-dependencies]
Werkzeug = "2.0.3"
pyparsing = "2.4.7"
tensorflow = "^2.8.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
