repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-merge-conflict
      - id: check-added-large-files
      - id: check-ast
      - id: check-symlinks
      - id: check-yaml
        args: ['--unsafe']
      - id: trailing-whitespace
      - id: check-json
      - id: debug-statements
      - id: detect-aws-credentials
        args:
        - --allow-missing-credentials
      - id: pretty-format-json
        args:
        - --autofix
        exclude: Pipfile.lock
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: ["--profile", "black"]
  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        additional_dependencies: [ flake8-print ]
        files: '\.py$'
        args:
          - --select=F401,F403,F406,F821,T003
  - repo: https://github.com/humitos/mirrors-autoflake
    rev: v1.3
    hooks:
      - id: autoflake
        files: '\.py$'
        exclude: '^\..*'
        args: ["--in-place", "--remove-all-unused-imports"]
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        args: ["--target-version", "py310"]
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.31.1
    hooks:
      - id: pyupgrade
        args: [--py37-plus]