language: Snakemake
name: sequana_depletion
description: A short description
url: https://github.com/sequana/sequana_depletion/blob/master/sequana_pipelines/depletion/depletion.rules
categories: [NGS, snakemake, sequana]
authors:
    - firstname: Thomas
      lastname: Cokelaer
      email: thomas.cokelaer@pasteur.fr

