[tool.poetry]
name = "clone-all-from-org"
version = "0.2.2"
description = "CLI tool to clone all repos from a given organization or user"
authors = ["Michael Twomey <mick@twomeylee.name>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/micktwomey/clone-all-from-org"
repository = "https://github.com/micktwomey/clone-all-from-org"
include = ["CHANGELOG.md", "justfile", "noxfile.py"]

[tool.poetry.dependencies]
python = ">=3.9,<4.0"
structlog = "^21.5"
typer = "^0.4"
rich = "^12.0"
click = "^8.1"
gidgethub = "^5.1"
httpx = "^0.22"
clone-repo = ">=0.2.0,<1.0.0"
PyYAML = "^6.0"
pydantic = "^1.9"
types-PyYAML = "^6.0"
aioitertools = "^0.10.0"

[tool.poetry.dev-dependencies]
black = "^22.1"
mypy = "^0.941"
pytest = "^7.1"
isort = "^5.10"
pre-commit = "^2.17"
nox = "^2022.1"
changelog-manager = "^1.3"
types-PyYAML = "^6.0.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"

[tool.mypy]
strict = true
plugins = "pydantic.mypy"

[tool.poetry.scripts]
clone-all-from-org = 'clone_all_from_org.main:app'
