
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-17T21:08:19+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "d7e9ed0d559d8fbcf03c59eef845f1bdfa54697d",
 "version": "0.1.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
