before_script:
  - pip install '.[test]'

test_job_py310:
  image: python:3.10
  script:
    - pytest
  stage: test

test_job_py39:
  image: python:3.9
  script:
    - pytest
  stage: test

test_job_py38:
  image: python:3.8
  script:
    - pytest
  stage: test

test_job_py37:
  image: python:3.7
  script:
    - pytest
  stage: test

test_job_integration:
  image: fedora:32
  before_script:
    - dnf install -y dbus-daemon python3-pip
    - pip install '.[test,trio]'
  script:
    - dbus-run-session -- pytest
  stage: test
