[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "jeepney"
author = "Thomas Kluyver"
author-email = "thomas@kluyver.me.uk"
home-page = "https://gitlab.com/takluyver/jeepney"
description-file = "README.rst"
requires-python = ">=3.7"
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Topic :: Desktop Environment"
]

[tool.flit.metadata.requires-extra]
test = [
    "pytest",
    "pytest-trio",
    "pytest-asyncio >=0.17",
    "testpath",
    "trio",
    "async-timeout",
]
trio = [
    "trio",
    "async_generator; python_version == '3.6'",
]

[tool.flit.metadata.urls]
Documentation = "https://jeepney.readthedocs.io/en/latest/"

