
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-01T17:35:05+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "51b0110ed198165af13a9ddd8a8b07c7b204f602",
 "version": "0.1.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
