
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-05T11:47:18+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "0d09f68b6ee068c658b65a24fd6244dd9d606ba2",
 "version": "0.7.1.post.dev507"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
