
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-04T03:47:18+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "9334668b6d753b237c0276f27d3c7c721e1c30ad",
 "version": "0.0.71.post0.dev130"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
