# Config file for automatic testing at travis-ci.org
dist: xenial
language: python

sudo: false
python:
  - "3.10-dev"
  - "3.9"
  - "3.8"
  - "3.7"
  - "3.6"
env:
  - DJANGO="Django>=3.2,<3.3"
  - DJANGO="Django>=3.1,<3.2"
  - DJANGO="Django>=3,<3.1"
  - DJANGO="Django>=2.2,<2.3"
before_install:
  - pip install -q $DJANGO
install:
  - python setup.py develop
  - pip install -r requirements.test.txt .
script:
  - ./example/manage.py test
after_success:
  - coveralls
matrix:
  exclude:
