
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-05T12:10:13+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "843b571939fe389273f2ae616e27f81089e3815b",
 "version": "0.7.1.post.dev513"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
