
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-05T13:35:12-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "40e2e2bd1c1de5651bc7fb484c823e43cfc69877",
 "version": "1.2.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
