
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-02T22:19:44+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "3b7e40aa0c49e6465ac392a7192669dce653513f",
 "version": "0.0.71.post0.dev126"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
