
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-05T17:10:51+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "a1e4d9a68f04c1486dc331e3b55c9c6ca2631440",
 "version": "0.18"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
