
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-07T15:40:48+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "55e4032722b2f316ec44b50afb83653f8083cc3d",
 "version": "2.5.28.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
