
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-04T12:03:43-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "23b4e06bc0e18ac3312a5c2ecf42347b760ee863",
 "version": "1.38.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
