
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-31T20:06:25+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "e60cfb57d45663f36ee6010ad18829322d373a30",
 "version": "2.5.3.dev20220404"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
