from typing import List

def copy_directory(source_directory: str, target_directory: str) -> None: ...
def file_names_in_directory(path: str): ...
def directory_names_in_directory(path: str): ...
def file_paths_in_directory(path: str) -> List[str]: ...
def file_paths_in_directory_with_extension(path: str, file_extensions: List[str]) -> List[str]: ...
def get_latest_file_in_directory(path: str): ...
def clean_directory(path: str, recursive: bool = ...): ...
