[tool.poetry]
name = "wheat"
version = "0.5.0"
description = "A concise and fast CLI to log hours in Harvest."
authors = ["etschz <ethanschmitz214@gmail.com>"]
license = "MIT"

readme = "README.md"
repository = "https://github.com/etschz/wheat"

keywords = ["time", "harvest", "zoom", "calendar", "wheat"]

classifiers = ["Topic :: Software Development :: Libraries :: Python Modules"]

[tool.poetry.dependencies]
python = "^3.8"
google-api-python-client = "^2.42.0"
google-auth-httplib2 = "^0.1.0"
google-auth-oauthlib = "^0.5.1"
pendulum = "^2.1.2"
tomlkit = "^0.10.1"
cleo = "1.0.0a4"

[tool.poetry.dev-dependencies]
pre-commit = "^2.17.0"
pytest = "^7.1.1"
tox = "^3.24.5"
pytest-cov = "^3.0.0"
pytest-sugar = "^0.9.4"
httpretty = "^1.1.4"
pytest-mock = "^3.7.0"
black = {version = "^22.3.0", allow-prereleases = true}
sure = "^2.0.0"

[tool.poetry.scripts]
wheat = "wheat.console.application:main"

[tool.isort]
py_version = 39
profile = "black"
force_single_line = true
combine_as_imports = true
lines_between_types = 1
lines_after_imports = 2
src_paths = ["src", "tests"]
extend_skip = ["setup.py"]

[tool.black]
target-version = ["py39"]
preview = true
line-length = 90 # 72 is python's standard. Change locally if you want.

[tool.coverage.report]
exclude_lines = [
    'if __name__ == "__main__":',
    "if TYPE_CHECKING:"
]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
