
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-02T10:17:09+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "3144c45712abedd3ff9a208bcd1b5cef95455d25",
 "version": "0.9.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
