# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: strmprivacy/api/installations/v1/installations_v1.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import field_behavior_pb2 as google_dot_api_dot_field__behavior__pb2
from strmprivacy.api.installations.v1 import entities_v1_pb2 as strmprivacy_dot_api_dot_installations_dot_v1_dot_entities__v1__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n7strmprivacy/api/installations/v1/installations_v1.proto\x12 strmprivacy.api.installations.v1\x1a\x1fgoogle/api/field_behavior.proto\x1a\x32strmprivacy/api/installations/v1/entities_v1.proto\"\x18\n\x16GetInstallationRequest\"d\n\x17GetInstallationResponse\x12I\n\x0cinstallation\x18\x01 \x01(\x0b\x32..strmprivacy.api.installations.v1.InstallationB\x03\xe0\x41\x02\x32\x9f\x01\n\x14InstallationsService\x12\x86\x01\n\x0fGetInstallation\x12\x38.strmprivacy.api.installations.v1.GetInstallationRequest\x1a\x39.strmprivacy.api.installations.v1.GetInstallationResponseBx\n#io.strmprivacy.api.installations.v1P\x01ZOgithub.com/strmprivacy/api-definitions-go/v2/api/installations/v1;installationsb\x06proto3')



_GETINSTALLATIONREQUEST = DESCRIPTOR.message_types_by_name['GetInstallationRequest']
_GETINSTALLATIONRESPONSE = DESCRIPTOR.message_types_by_name['GetInstallationResponse']
GetInstallationRequest = _reflection.GeneratedProtocolMessageType('GetInstallationRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETINSTALLATIONREQUEST,
  '__module__' : 'strmprivacy.api.installations.v1.installations_v1_pb2'
  # @@protoc_insertion_point(class_scope:strmprivacy.api.installations.v1.GetInstallationRequest)
  })
_sym_db.RegisterMessage(GetInstallationRequest)

GetInstallationResponse = _reflection.GeneratedProtocolMessageType('GetInstallationResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETINSTALLATIONRESPONSE,
  '__module__' : 'strmprivacy.api.installations.v1.installations_v1_pb2'
  # @@protoc_insertion_point(class_scope:strmprivacy.api.installations.v1.GetInstallationResponse)
  })
_sym_db.RegisterMessage(GetInstallationResponse)

_INSTALLATIONSSERVICE = DESCRIPTOR.services_by_name['InstallationsService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n#io.strmprivacy.api.installations.v1P\001ZOgithub.com/strmprivacy/api-definitions-go/v2/api/installations/v1;installations'
  _GETINSTALLATIONRESPONSE.fields_by_name['installation']._options = None
  _GETINSTALLATIONRESPONSE.fields_by_name['installation']._serialized_options = b'\340A\002'
  _GETINSTALLATIONREQUEST._serialized_start=178
  _GETINSTALLATIONREQUEST._serialized_end=202
  _GETINSTALLATIONRESPONSE._serialized_start=204
  _GETINSTALLATIONRESPONSE._serialized_end=304
  _INSTALLATIONSSERVICE._serialized_start=307
  _INSTALLATIONSSERVICE._serialized_end=466
# @@protoc_insertion_point(module_scope)
