# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://pages.github.DevTransferApp.com./devtransfer/devtransfer/"

git_url = "https://github.DevTransferApp.com/devtransfer/devtransfer/tree/main/"

def custom_doc_links(name): return None
