name: CI
on: [push, pull_request]
jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [
          '3.8',
          '3.9',
          '3.10',
        ]

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Setup package
      run: python -m pip install .[dev]

    - name: Run test
      run: |
        pytest -vvv
