[project]
name = "yapper"
version = "0.2.0b9"
description = "Parser for converting python docstrings to .astro files for the Astro static site generator."
readme = "README.md"
requires-python = ">=3.9,<4.0"
keywords = [
    "python",
    "static-site-generator",
    "astro",
    "parser",
    "documentation",
    "docstrings",
]
authors = [
    { name = "Gareth Simons", email = "info@benchmarkurbanism.com" },
]
maintainers = [
    { name = "Gareth Simons", email = "info@benchmarkurbanism.com" },
]
classifiers = [
    "Programming Language :: Python",
]
dependencies = [
    "docstring-parser<1.0,>=0.13",
    "dominate<3.0.0,>=2.6.0",
    "python-slugify<7.0.0,>=6.1.1",
    "Markdown<4.0.0,>=3.3.6",
    "pyyaml>=6.0",
]

[project.license]
file = "LICENSE.txt"

[project.optional-dependencies]

[project.urls]
homepage = "https://github.com/benchmark-urbanism/yapper"
documentation = "https://github.com/benchmark-urbanism/yapper"
repository = "https://github.com/benchmark-urbanism/yapper"

[project.scripts]
yapper = "yapper.runner:cli"

[tool.pdm.dev-dependencies]
dev = [
    "pytest>=7.1.1",
]

[tool.pdm.scripts]
tests = "pytest ./tests"
publish = "pdm publish -u shongololo -v"

[build-system]
requires = [
    "pdm-pep517>=0.12.0",
    "tomli>=1.1.0",
]
build-backend = "pdm.pep517.api"
