[tool.poetry]
name = "gaul"
version = "0.4.0"
description = ""
authors = ["Jeff Shen <jshen2014@hotmail.com>"]
license = "MIT OR Apache-2.0"
readme = "README.rst"
homepage = "https://github.com/al-jshen/gaul"
repository = "https://github.com/al-jshen/gaul"
documentation = "https://gaul.readthedocs.io"
keywords = ["jax"]

[tool.poetry.dependencies]
python = "^3.9,<3.11"
jax = "^0.3.1"
jaxlib = "^0.3.0"
tqdm = "^4.62.3"

[tool.poetry.dev-dependencies]
pytest = "^7.0.1"
pytest-cov = "^3.0.0"
coverage = {extras = ["toml"], version = "^6.3.2"}
codecov = "^2.1.12"
isort = "^5.10.1"
jupyterlab = "^3.2.9"
matplotlib = "^3.5.1"
seaborn = "^0.11.2"
corner = "^2.2.1"
ipywidgets = "^7.6.5"
docformatter = "^1.4"
arviz = "^0.11.4"
Sphinx = "^4.4.0"
tensorflow = "^2.8.0"
tbp-nightly = "^2.5.0-alpha.20210511"

[tool.coverage.paths]
source = ["gaul", "*/site-packages"]

[tool.coverage.run]
parallel = true
branch = true
source = ["gaul"]
omit = [
  "docs/*",
  "tests/*",
  "*__init__*"
]

[tool.coverage.report]
show_missing = true
exclude_lines = [
    "raise NotImplementedError",
    "raise ImportError",
    "except ImportError",
    "def __len__",
    "def __repr__",
    "logging.warning",
    "deprecation_warning",
    "deprecated",
    "if tqdm is None"
]

[tool.isort]
profile = "black"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
