[tool.poetry]
name = "useful-utilities"
version = "1.0.1"
description = "Various useful utilities that I created when I didn't find an alternative."
homepage = "https://github.com/lzrdblzzrd/useful-utilities"
repository = "https://github.com/lzrdblzzrd/useful-utilities"
keywords = ["lzrdblzzrd", "useful", "utilities"]
authors = ["lzrdblzzrd <lzrdblzzrd@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.27.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
