[tool.poetry]
name = "dh2vrml"
version = "0.1.11"
description = "Library and CLI tool to convert Denavit-Hartenberg parameters to an X3D model"
authors = ["Jasper Chan <jasperchan515@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/Gigahawk/dh2vrml"
repository = "https://github.com/Gigahawk/dh2vrml"

[tool.poetry.dependencies]
python = "^3.8,<3.11"
x3d = "^4.0.47"
xmlschema = "^1.9.2"
numpy = "^1.21"
PyYAML = "^6.0"
click = "^8.0.3"
pandas = "^1.3"
scipy = "^1.7.0"
toml = "^0.10.2"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[tool.poetry.scripts]
dh2vrml = 'dh2vrml.cli:main'

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
