
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-05T22:26:54+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "854510a4a354be9df43c94ba9fc390a81ddf483e",
 "version": "0.4.138"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
