# coding: utf-8

"""
    Internal API

    SmartDiagnostics REST API for internal users only  # noqa: E501

    OpenAPI spec version: v3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import smart_diagnostics_client
from smart_diagnostics_client.api.kcf_academy_api import KcfAcademyApi  # noqa: E501
from smart_diagnostics_client.rest import ApiException


class TestKcfAcademyApi(unittest.TestCase):
    """KcfAcademyApi unit test stubs"""

    def setUp(self):
        self.api = KcfAcademyApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_kcf_academy_token(self):
        """Test case for get_kcf_academy_token

        Generates auto token for KCF Academy (Docebo).  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
