[tool.poetry]
name = "postgresqlite"
version = "0.1.1"
description = "Python package that gives you the power of a PostgreSQL server, with the convenience of the sqlite3 package."
authors = ["Frank van Viegen <pp@vanviegen.net>"]

[tool.poetry.dependencies]
python = "^3.10"
pg8000 = "^1.24.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

