[tool.poetry]
name = "httpunixsocketconnection"
version = "1.0.0"
description = "Really small Python class that extends native http.client.HTTPConnection allowing sending HTTP requests to Unix Sockets"
authors = ["Marek Sierociński <mareksierocinski@gmail.com>"]
license = "Apache-2.0"

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
