
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-31T09:52:44-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "6373632267c9bf37166a17fd6bc0b3ed079be947",
 "version": "1.4.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
