repos:
-   repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.10
    hooks:
    -   id: forbid-crlf
    -   id: remove-crlf
    -   id: forbid-tabs
    -   id: remove-tabs
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-merge-conflict
    - id: check-yaml
      args: [--unsafe]
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.9.3
    hooks:
    - id: isort
-   repo: https://github.com/ambv/black
    rev: 21.9b0
    hooks:
    - id: black
      language_version: python3.8
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    - id: flake8
        additional_dependencies: [flake8-typing-imports==1.10.0]
-   repo: https://github.com/Lucas-C/pre-commit-hooks-bandit
    rev: v1.0.5
    hooks:
    -  id: python-bandit-vulnerability-check
    args: [--skip, "B101", --recursive, python_boilerplate]
-   repo: https://github.com/nbQA-dev/nbQA
    rev: 1.2.2
    hooks:
    -   id: nbqa-black
    -   id: nbqa-flake8
    -   id: nbqa-pyupgrade
        args: [--py37-plus]
    -   id: nbqa-isort