
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-04T13:52:15-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "2a51f0609778eec90cada2daaf6dad64e65b7e7d",
 "version": "1.38.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
