[tool.poetry]
name = "znotify"
version = "0.0.1"
description = "sdk for notify"
authors = ["Zxilly <zhouxinyu1001@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
requests = "^2.27.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
