[tool.poetry]
name = "murraytait_cdktf"
version = "0.5.5"
description = ""
authors = ["Murray Tait <6074789+deathtumble@users.noreply.github.com>"]
packages = [
    { include = "murraytait_cdktf" }
]

[tool.poetry.dependencies]
python = "^3.8"
constructs = "^10.0.29"
cdktf = "^0.9.2"
cdktf-cdktf-provider-aws = "^5.0.26"
boto3 = "^1.20.31"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
autopep8 = "^1.6.0"
pytest-mock = "^3.6.1"
mock = "^4.0.3"
pytest-html = "^3.1.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
