# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tracdap/metadata/model.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from tracdap.metadata import type_pb2 as tracdap_dot_metadata_dot_type__pb2
from tracdap.metadata import data_pb2 as tracdap_dot_metadata_dot_data__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1ctracdap/metadata/model.proto\x12\x10tracdap.metadata\x1a\x1btracdap/metadata/type.proto\x1a\x1btracdap/metadata/data.proto\"\x99\x01\n\x0eModelParameter\x12\x33\n\tparamType\x18\x01 \x01(\x0b\x32 .tracdap.metadata.TypeDescriptor\x12\r\n\x05label\x18\x02 \x01(\t\x12\x32\n\x0c\x64\x65\x66\x61ultValue\x18\x03 \x01(\x0b\x32\x17.tracdap.metadata.ValueH\x00\x88\x01\x01\x42\x0f\n\r_defaultValue\"F\n\x10ModelInputSchema\x12\x32\n\x06schema\x18\x01 \x01(\x0b\x32\".tracdap.metadata.SchemaDefinition\"G\n\x11ModelOutputSchema\x12\x32\n\x06schema\x18\x01 \x01(\x0b\x32\".tracdap.metadata.SchemaDefinition\"\xbd\x04\n\x0fModelDefinition\x12\x10\n\x08language\x18\x01 \x01(\t\x12\x12\n\nrepository\x18\x02 \x01(\t\x12\x0c\n\x04path\x18\x03 \x01(\t\x12\x12\n\nentryPoint\x18\x05 \x01(\t\x12\x0f\n\x07version\x18\x06 \x01(\t\x12\x45\n\nparameters\x18\x07 \x03(\x0b\x32\x31.tracdap.metadata.ModelDefinition.ParametersEntry\x12=\n\x06inputs\x18\x08 \x03(\x0b\x32-.tracdap.metadata.ModelDefinition.InputsEntry\x12?\n\x07outputs\x18\t \x03(\x0b\x32..tracdap.metadata.ModelDefinition.OutputsEntry\x1aS\n\x0fParametersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12/\n\x05value\x18\x02 \x01(\x0b\x32 .tracdap.metadata.ModelParameter:\x02\x38\x01\x1aQ\n\x0bInputsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x31\n\x05value\x18\x02 \x01(\x0b\x32\".tracdap.metadata.ModelInputSchema:\x02\x38\x01\x1aS\n\x0cOutputsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x32\n\x05value\x18\x02 \x01(\x0b\x32#.tracdap.metadata.ModelOutputSchema:\x02\x38\x01J\x04\x08\x04\x10\x05R\x07packageB\x1e\n\x1aorg.finos.tracdap.metadataP\x01\x62\x06proto3')



_MODELPARAMETER = DESCRIPTOR.message_types_by_name['ModelParameter']
_MODELINPUTSCHEMA = DESCRIPTOR.message_types_by_name['ModelInputSchema']
_MODELOUTPUTSCHEMA = DESCRIPTOR.message_types_by_name['ModelOutputSchema']
_MODELDEFINITION = DESCRIPTOR.message_types_by_name['ModelDefinition']
_MODELDEFINITION_PARAMETERSENTRY = _MODELDEFINITION.nested_types_by_name['ParametersEntry']
_MODELDEFINITION_INPUTSENTRY = _MODELDEFINITION.nested_types_by_name['InputsEntry']
_MODELDEFINITION_OUTPUTSENTRY = _MODELDEFINITION.nested_types_by_name['OutputsEntry']
ModelParameter = _reflection.GeneratedProtocolMessageType('ModelParameter', (_message.Message,), {
  'DESCRIPTOR' : _MODELPARAMETER,
  '__module__' : 'tracdap.metadata.model_pb2'
  # @@protoc_insertion_point(class_scope:tracdap.metadata.ModelParameter)
  })
_sym_db.RegisterMessage(ModelParameter)

ModelInputSchema = _reflection.GeneratedProtocolMessageType('ModelInputSchema', (_message.Message,), {
  'DESCRIPTOR' : _MODELINPUTSCHEMA,
  '__module__' : 'tracdap.metadata.model_pb2'
  # @@protoc_insertion_point(class_scope:tracdap.metadata.ModelInputSchema)
  })
_sym_db.RegisterMessage(ModelInputSchema)

ModelOutputSchema = _reflection.GeneratedProtocolMessageType('ModelOutputSchema', (_message.Message,), {
  'DESCRIPTOR' : _MODELOUTPUTSCHEMA,
  '__module__' : 'tracdap.metadata.model_pb2'
  # @@protoc_insertion_point(class_scope:tracdap.metadata.ModelOutputSchema)
  })
_sym_db.RegisterMessage(ModelOutputSchema)

ModelDefinition = _reflection.GeneratedProtocolMessageType('ModelDefinition', (_message.Message,), {

  'ParametersEntry' : _reflection.GeneratedProtocolMessageType('ParametersEntry', (_message.Message,), {
    'DESCRIPTOR' : _MODELDEFINITION_PARAMETERSENTRY,
    '__module__' : 'tracdap.metadata.model_pb2'
    # @@protoc_insertion_point(class_scope:tracdap.metadata.ModelDefinition.ParametersEntry)
    })
  ,

  'InputsEntry' : _reflection.GeneratedProtocolMessageType('InputsEntry', (_message.Message,), {
    'DESCRIPTOR' : _MODELDEFINITION_INPUTSENTRY,
    '__module__' : 'tracdap.metadata.model_pb2'
    # @@protoc_insertion_point(class_scope:tracdap.metadata.ModelDefinition.InputsEntry)
    })
  ,

  'OutputsEntry' : _reflection.GeneratedProtocolMessageType('OutputsEntry', (_message.Message,), {
    'DESCRIPTOR' : _MODELDEFINITION_OUTPUTSENTRY,
    '__module__' : 'tracdap.metadata.model_pb2'
    # @@protoc_insertion_point(class_scope:tracdap.metadata.ModelDefinition.OutputsEntry)
    })
  ,
  'DESCRIPTOR' : _MODELDEFINITION,
  '__module__' : 'tracdap.metadata.model_pb2'
  # @@protoc_insertion_point(class_scope:tracdap.metadata.ModelDefinition)
  })
_sym_db.RegisterMessage(ModelDefinition)
_sym_db.RegisterMessage(ModelDefinition.ParametersEntry)
_sym_db.RegisterMessage(ModelDefinition.InputsEntry)
_sym_db.RegisterMessage(ModelDefinition.OutputsEntry)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\032org.finos.tracdap.metadataP\001'
  _MODELDEFINITION_PARAMETERSENTRY._options = None
  _MODELDEFINITION_PARAMETERSENTRY._serialized_options = b'8\001'
  _MODELDEFINITION_INPUTSENTRY._options = None
  _MODELDEFINITION_INPUTSENTRY._serialized_options = b'8\001'
  _MODELDEFINITION_OUTPUTSENTRY._options = None
  _MODELDEFINITION_OUTPUTSENTRY._serialized_options = b'8\001'
  _MODELPARAMETER._serialized_start=109
  _MODELPARAMETER._serialized_end=262
  _MODELINPUTSCHEMA._serialized_start=264
  _MODELINPUTSCHEMA._serialized_end=334
  _MODELOUTPUTSCHEMA._serialized_start=336
  _MODELOUTPUTSCHEMA._serialized_end=407
  _MODELDEFINITION._serialized_start=410
  _MODELDEFINITION._serialized_end=983
  _MODELDEFINITION_PARAMETERSENTRY._serialized_start=717
  _MODELDEFINITION_PARAMETERSENTRY._serialized_end=800
  _MODELDEFINITION_INPUTSENTRY._serialized_start=802
  _MODELDEFINITION_INPUTSENTRY._serialized_end=883
  _MODELDEFINITION_OUTPUTSENTRY._serialized_start=885
  _MODELDEFINITION_OUTPUTSENTRY._serialized_end=968
# @@protoc_insertion_point(module_scope)
