
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-08T11:00:15+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "f4df80587e34a485c921cfc6e35d3cbbfb8b1c44",
 "version": "v1.5.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
