
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-04T17:16:14-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "a2df2d024e635c7d4eb601f765deba8f3015d55d",
 "version": "0.0.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
