site_name: chromatic
site_url: https://zkbt.github.com/chromatic
nav:
    #- Home: index.md
    - installation.ipynb
    - quickstart.ipynb
    - basics.ipynb
    - io.ipynb
    - creating.ipynb
    - actions.ipynb
    - visualizing.ipynb
    - multi.ipynb
    - api.md
theme:
  name: "material"
  features:
      - navigation.tracking
repo_url: https://github.com/zkbt/chromatic/
plugins:
  - search
  - mkdocs-jupyter:
      execute : True
      include_source : True
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          selection:
            docstring_style: "numpy"
          rendering:
            show_source: False
      custom_templates: templates
      watch:
        - chromatic
  - exclude:
      glob:
        - "example-datasets/*"
        - "*.pdf"

# this is super borrowed from Christina Hedges' fabulous
# https://christinahedges.github.io/astronomy_workflow/
