
 

// This file is autogenerated. DO NOT EDIT

#pragma once
#include <robotpy_build.h>


#include <../../_impl/include/frc/motorcontrol/MotorController.h>




#include <rpygen/frc__SpeedController.hpp>

namespace rpygen {

using namespace frc;


template <typename CfgBase>
using PyTrampolineCfgBase_frc__MotorController =
    PyTrampolineCfg_frc__SpeedController<
CfgBase
>;

template <typename CfgBase = EmptyTrampolineCfg>
struct PyTrampolineCfg_frc__MotorController :
    PyTrampolineCfgBase_frc__MotorController< CfgBase>
{
    using Base = frc::MotorController;

};


template <typename PyTrampolineBase, typename PyTrampolineCfg>
using PyTrampolineBase_frc__MotorController =
    PyTrampoline_frc__SpeedController<
        PyTrampolineBase
        
        , PyTrampolineCfg
    >
;

template <typename PyTrampolineBase, typename PyTrampolineCfg>
struct PyTrampoline_frc__MotorController : PyTrampolineBase_frc__MotorController<PyTrampolineBase, PyTrampolineCfg> {
    using PyTrampolineBase_frc__MotorController<PyTrampolineBase, PyTrampolineCfg>::PyTrampolineBase_frc__MotorController;






};

}; // namespace rpygen
