[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "ckpt"
authors = [{name = "Holger Hoefling", email = "hhoeflin@gmail.com"}]
license = {file = "LICENSE"}
classifiers = ["License :: OSI Approved :: MIT License"]
dynamic = ["version", "description"]
requires-python = ">=3.8"

dependencies = [
    "GitPython >=3.1.27",
    "typer >=0.4.0",
    "dill >=0.3.4",
]

[project.optional-dependencies]
dev = [
    "pytest >=6.2.5",
    "pytest-pudb >=0.7.0",
    "pudb >=2021.2.2",
    "ipython >=7.30.1",
    "bpython >=0.22.1",
    "ipdb >=0.13.9",
    "flakehell >= 0.9.0",
]

[project.urls]
Home = "https://hhoeflin.github.io/ckpt/"

[project.scripts]
checkpoint = "ckpt.main:app"

[tool.black]
line-length = 88

[tool.flakehell]
max-line-length = 88

[tool.pyright]
include = ["checkpoint", "tests"]
