[tool.pytest.ini_options]
addopts = "--doctest-modules -x --nbmake"
usefixtures = "before_test"
norecursedirs = [
    "tested project",
    "dist",
    "build",
    "venv"
]
doctest_optionflags = "NORMALIZE_WHITESPACE NUMBER ELLIPSIS IGNORE_EXCEPTION_DETAIL"


[tool.black]
line-length = 110

