
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-01T19:30:27+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "afb5a928f60354354309bf4db9135c3347f384be",
 "version": "v0.6.7a3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
