from nwon_baseline.typings import TerminalColors as TerminalColors

def print_green(text: str): ...
def print_blue(text: str): ...
def print_cyan(text: str): ...
def print_warning(text: str): ...
def print_error(text: str): ...
def print_color(text: str, color: TerminalColors) -> None: ...
