
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-01T16:50:19+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "619211a4af2619457bbe2dccf75d8f68dbfc630f",
 "version": "1.38.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
