
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-03T13:44:51-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "b983280473a752ba9b726813b791dc954a38dc5b",
 "version": "0.0.22"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
