
# This workflow will upload a Python Package using the PyPi action workflow

name: Upload Python Package

on:
  release:
    types: [published]

env:
  VERMOUTH_TEST_DSSP: mkdssp
  SKIP_GENERATE_AUTHORS: 1
  SKIP_WRITE_GIT_CHANGELOG: 1

jobs:
  build:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
       py_version: ["3.6", "3.7", "3.8", "3.9"] 
       include:
         - py_version: "3.6"
           WITH_CODECOV: true
           WITH_SCIPY: true
         - py_version: "3.7"
           WITH_CODECOV: true
           WITH_SCIPY: true
         - py_version: "3.8"
           WITH_CODECOV: true
           WITH_SCIPY: true
         - py_version: "3.9"
           WITH_CODECOV: true
           WITH_SCIPY: false
           
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.py_version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.py_version }}
    - name: Install dependencies part I
      run: |
        sudo apt-get install dssp
        pip install --upgrade setuptools pip
    - if: ${{ matrix.WITH_SCIPY }}
      name: Install scipy
      run: |
        pip install scipy
    - name: Install package and requirements
      run: |
        pip install --upgrade .
        pip install -r requirements-tests.txt
        
    - name: Run pytest with codecoverage
      run: |
        coverage run --source=vermouth $(which pytest) -vv vermouth --hypothesis-show-statistics
        coverage report --omit='*/bin/pytest'
        
    - if: ${{ matrix.WITH_CODECOV }}
      name: Report code coverage 
      run: |
        codecov
        
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        pip install --upgrade setuptools pip
        pip install --upgrade .
        pip install -r requirements-tests.txt
    - name: Run pylint 
      run: |
         pylint --disable=fixme --fail-under=8.0 vermouth
         pylint --disable=fixme --fail-under=9.0 bin/martinize2 
         
   
  docs:
      runs-on: ubuntu-latest
      
      steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
           python-version: 3.9
      - name: Install dependencies
        run: |
          pip install --upgrade setuptools pip
          pip install --upgrade .
          pip install -r requirements-docs.txt
          
      - name: Run docs
        run: | 
          mkdir -p doc/source/_static
          sphinx-build -EnW -b html doc/source/ doc/build/html
  
  
  deploy:
    needs: [build, lint, docs]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
        
    - name: Install pypa/build
      run: >-
        python -m
        pip install
        build
        --user
        pip install pbr
         
    - name: Build a binary wheel and a source tarball
      run: >-
        python -m
        build
        --sdist
        --wheel
        --outdir dist/
        
    - name: Publish package to PyPI
      uses: pypa/gh-action-pypi-publish@master      
      with:
       user: __token__
       password: ${{ secrets.PYPI_API_TOKEN }}
