
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-03T13:37:13-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "8b7b19e4a7352d166df6b82586be9ac6dfc392bb",
 "version": "0.0.21"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
