
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-01T11:29:02+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "bdf024c154ef82da129280321adbdd8522216fae",
 "version": "0.7.1.post.dev495"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
