[tool.poetry]
name = "mbox"
version = "0.1.11"
description = "Personal Python toolbox for quick prototyping."
authors = ["Maxime Mouchet <max@maxmouchet.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/maxmouchet/mbox"

[tool.poetry.dependencies]
python = "^3.7"
appdirs = "^1.4.4"
click = {version = "^8.1.2", optional = true}
dateparser = {version = "^1.1.1", optional = true}
requests = {version = "^2.27.1", optional = true}

[tool.poetry.dev-dependencies]
hypothesis = {version = "^6.41.0", extras = ["pytz"]}
bumpversion = "^0.6.0"
mypy = "^0.942"
pre-commit = "^2.18.1"
pytest = "^7.1.1"
pytest-cov = "^3.0.0"
sphinx = "^4.5.0"

[tool.poetry.extras]
click = ["click", "dateparser"]
requests = ["requests"]

[tool.pytest.ini_options]
addopts = "--cov=mbox --cov-report=xml"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
