[tool.poetry]
name = "text-dedup"
version = "0.0.13"
description = ""
authors = ["Chenghao Mou <mouchenghao@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.7,<3.10"
numpy = "1.22.3"
datasketch = "^1.5.7"
nltk = "^3.7"
torch = "^1.11.0"
simhash = "^2.1.2"
annoy = "^1.17.0"
scipy = "1.7.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
