
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-04T10:36:39-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "e4c16db7f59e0f243965f015e95996f9e7fe9665",
 "version": "2022.3.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
