# Generated by Django 3.2 on 2021-08-23 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='filename',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='timestamp',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
