
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-01T16:30:33+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "dc19f95ac0fba437ed3676f214ac7f6c07dbc5f3",
 "version": "0.4.125"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
