[tool.poetry]
name = "search_placeholder"
version = "0.2.0"
description = "Auto add placeholder content for django admin"
authors = ["Waket Zheng <waketzheng@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/waketzheng/django-search-placeholder"
repository = "https://github.com/waketzheng/django-search-placeholder"
keywords = ["django", "search", "placeholder"]
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Development Status :: 3 - Alpha",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3 :: Only",
    "Operating System :: POSIX",
    "Environment :: Web Environment",
    "Intended Audience :: Developers",
    "Topic :: Software Development",
    "Topic :: Software Development :: Libraries",
    "Framework :: Django",
]
include = [
    "LICENSE",
]

[tool.poetry.dependencies]
python = "^3.8"
Django = "^4.0"

[tool.poetry.dev-dependencies]
black = "^21.10b0"
isort = "^5.10.0"
mypy = "^0.910"
bandit = "^1.7.0"
flake8 = "^4.0.1"
coverage = "^6.1.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 88
py38 = true
exclude = '''
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.mypy_cache
    | \.pytest_cache
    | \.tox
    | \.venv
'''

[tool.isort]
profile = "black"
known_third_party = "django"
skip = "build,.tox,.venv,.git,.pytest_cache,.mypy_cache"
multi_line_output = 5
include_trailing_comma = true
force_grid_wrap = 0
force_single_line = false
balanced_wrapping = true
use_parentheses = true

[tool.coverage]
    [tool.coverage.report]
    include = ['search_placeholder']

[tool.tox]
legacy_tox_ini = """
[gh-actions]
python =
    3.8: py38
    3.9: py39
    3.10: py310

[tox]
envlist = py38, py39, py310
isolated_build = True

[testenv]
commands =
    pip install -r dev_requirements.txt
    coverage run --source search_placeholder -m pytest
passenv = CI
"""

[tool.mypy]
disable_error_code = "override"
