[tool.poetry]
name = "PyMine-Server"
version = "0.0.0"
description = "A fast and easy to use, moddable, Python based Minecraft server!"
authors = ["Milo Weinberg <iapetus011@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
