#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['foodx_backup_source']

package_data = \
{'': ['*']}

install_requires = \
['aiofiles ~=0.8.0',
 'aiohttp ~=3.8.1',
 'click ~=8.1.2',
 'deepmerge ~=1.0.1',
 'gitpython ~=3.1.27',
 'pydantic ~=1.9.0',
 'ruamel.yaml ~=0.17.20']

extras_require = \
{'dev': ['build_harness ~=1.0.1',
         'pre_commit ~=2.17.0',
         'types-aiofiles ~=0.8.3'],
 'doc': ['sphinx ~=4.5.0', 'sphinx_rtd_theme ~=1.0'],
 'test': ['pytest ~=7.1.1',
          'pytest-asyncio ~=0.18.3',
          'pytest-cov ~=3.0',
          'pytest-mock ~=3.7.0']}

entry_points = \
{'console_scripts': ['backup-source = foodx_backup_source.entrypoint:main']}

setup(name='foodx_backup_source',
      version='0.1.0.post1',
      description='A backup utility for FoodX source code.',
      author='FoodX Technologies',
      author_email='support@foodxtech.com',
      url='https://github.com/Food-X-Technologies/foodx_backup_source/',
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      extras_require=extras_require,
      entry_points=entry_points,
      python_requires='>=3.8',
     )
