
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-03T13:41:22-0500",
 "dirty": true,
 "error": null,
 "full-revisionid": "1e1a4e56c062da50d49cfc80a5a91e64345c935a",
 "version": "0.a3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
