from typing import List

def file_names_in_directory(path: str): ...
def directory_names_in_directory(path: str): ...
def file_paths_in_directory(path: str) -> List[str]: ...
def get_latest_file_in_directory(path: str): ...
def clean_directory(path: str, recursive: bool = ...): ...
