[build-system]
requires = ["setuptools>=46.4.0", "wheel", "packaging"]
build-backend = "setuptools.build_meta"

[tool.jupyter-releaser]
skip = ["check-links"]

[tool.jupyter-releaser.options]
ignore-glob = ["examples/**/*.*"]

[tool.tbump.version]
current = "0.7.0"
regex = '''
  (?P<major>\d+)\.(?P<minor>\d+)\.(?P<patch>\d+)
  ((?P<channel>a|b|rc|.dev)(?P<release>\d+))?
'''

[tool.tbump.git]
message_template = "Bump to {new_version}"
tag_template = "v{new_version}"

[[tool.tbump.file]]
src = "pytest_check_links/_version.py"

[tool.pytest.ini_options]
addopts = "-raXs --durations 10 --color=yes --doctest-modules"
filterwarnings = [
  "error",
]
pytester_example_dir = "examples"


[tool.mypy]
check_untyped_defs = true
disallow_subclassing_any = true
disallow_incomplete_defs = true
no_implicit_optional = true
pretty = true
show_error_context = true
show_error_codes = true
strict_equality = true
warn_unused_configs = true
warn_unused_ignores = true
warn_redundant_casts = true
exclude = [
    'setup.py'
]
