
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-02T13:25:05+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "c26bbd265406d26c47e5c7d68e9c7040baa4d201",
 "version": "1.1.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
