# Generated by Django 3.2.7 on 2022-04-03 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_user_informations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='informations',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
