[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "axforchemistry"
authors = [
    {name = "Sterling G. Baird", email = "sterling.baird@utah.edu"},
    {name="Ramsey Issa", email="u1374011@utah.edu"}
    ]
readme = "README.md"
classifiers = ["License :: OSI Approved :: MIT License"]
dynamic = ["version", "description"]

dependencies = [
    "numpy",
    "pandas",
    "plotly",
    "ax_platform>=0.2.4",
    "pyro-ppl==1.8.1",
    "tqdm",
    "matplotlib",
    "scipy",
    "ipython",
    "scikit_learn",
    ]

requires-python = ">=3.9"

[project.urls]
Home = "https://github.com/sparks-baird/AxForChemistry"
