
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-04T07:21:11-0600",
 "dirty": true,
 "error": null,
 "full-revisionid": "d9fc7c2784d6ca0303f1d839c52c97cf8ddc8477",
 "version": "0.5.10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
