
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-08T15:40:11+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "e1a012d7eb18c9d70d8f6528919b5b92ffa00b61",
 "version": "2644"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
