
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-04T18:26:21-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "fd9cc30d33e17d238fe1b914a2539a0702dafe16",
 "version": "3.3.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
