[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "algo-ops",
    "ocr-ops",
    "ezplotly",
    "numpy",
    "pandas",
    "pokemontcgsdk",
    "nose",
    "black",
    "bidict",
    "natsort",
    "requests"
]
build-backend = "setuptools.build_meta"