#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup


setup(name='remotv',
      version='0.0.2',
      description='More stuff coming',
      author=None,
      author_email=None,
      url=None,
      py_modules=['remotv'],
     )
