
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-31T10:25:28+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "f26313b07c5f1bc7678c71bcf5d3ddf80aadd02b",
 "version": "1.30"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
