[tool.poetry]
name = "zohavi"
version = "0.1.2"
description = ""
authors = ["pub12 <pubudu79@gmail.com>"]
packages = [ 
                { include = "zbase" },
                { include = "zcommon" },
            ]

            
[tool.poetry.dependencies]
python = "^3.8"
Flask = "^2.0.0"
Flask-Classful = "^0.14.2"
Flask-Login = "^0.6.0"
pytz = "^2022.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
