[tool.poetry]
name = "armadilloml"
version = "0.1.0"
description = ""
authors = ["Max Davish <mdavish@yext.com>"]

[tool.poetry.dependencies]
python = "^3.7"
requests = "^2.27.1"
rich = "^12.0.1"
click = "^8.0.4"
rich-click = "^1.2.1"

[tool.poetry.scripts]
armadilloml = "armadilloml:cli"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
