# -*- coding: utf-8 -*-

"""
firstlanguage_python

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
import os
from firstlanguage_python.utilities.schema_validator_wrapper import SchemaValidatorWrapper
from jsonschema import ValidationError
from firstlanguage_python.api_helper import APIHelper


class ApiQuestionResponse(object):

    """Implementation of the 'Api Question Response' model.

    TODO: type model description here.

    Attributes:
        answer (string): Answer to the question.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "answer": 'answer'
    }

    def __init__(self,
                 answer=None):
        """Constructor for the ApiQuestionResponse class"""

        # Initialize members of the class
        self.answer = answer

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        answer = dictionary.get('answer')

        # Return an object of this model
        return cls(answer)

    @classmethod
    def validate(cls, val):
        """Validates value against class schema

        Args:
            val: the value to be validated

        Returns:
            boolean : if value is valid against schema.

        """
        return SchemaValidatorWrapper.getValidator(APIHelper.get_schema_path(os.path.abspath(__file__))).is_valid(val)
