# -*- coding: utf-8 -*-

"""
firstlanguage_python

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
import os
from firstlanguage_python.utilities.schema_validator_wrapper import SchemaValidatorWrapper
from jsonschema import ValidationError
from firstlanguage_python.api_helper import APIHelper


class Errors1(object):

    """Implementation of the 'Errors1' model.

    TODO: type model description here.

    Attributes:
        msg (string): TODO: type description here.
        param (string): TODO: type description here.
        location (string): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "msg": 'msg',
        "param": 'param',
        "location": 'location'
    }

    def __init__(self,
                 msg=None,
                 param=None,
                 location=None):
        """Constructor for the Errors1 class"""

        # Initialize members of the class
        self.msg = msg
        self.param = param
        self.location = location

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        msg = dictionary.get('msg')
        param = dictionary.get('param')
        location = dictionary.get('location')

        # Return an object of this model
        return cls(msg,
                   param,
                   location)

    @classmethod
    def validate(cls, val):
        """Validates value against class schema

        Args:
            val: the value to be validated

        Returns:
            boolean : if value is valid against schema.

        """
        return SchemaValidatorWrapper.getValidator(APIHelper.get_schema_path(os.path.abspath(__file__))).is_valid(val)
