# -*- coding: utf-8 -*-

"""
firstlanguage_python

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
import os
from firstlanguage_python.utilities.schema_validator_wrapper import SchemaValidatorWrapper
from jsonschema import ValidationError
from firstlanguage_python.api_helper import APIHelper


class Responsestem(object):

    """Implementation of the 'responsestem' model.

    TODO: type model description here.

    Attributes:
        original_text (string): TODO: type description here.
        stem (string): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "original_text": 'originalText',
        "stem": 'stem'
    }

    def __init__(self,
                 original_text=None,
                 stem=None):
        """Constructor for the Responsestem class"""

        # Initialize members of the class
        self.original_text = original_text
        self.stem = stem

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        original_text = dictionary.get('originalText')
        stem = dictionary.get('stem')

        # Return an object of this model
        return cls(original_text,
                   stem)

    @classmethod
    def validate(cls, val):
        """Validates value against class schema

        Args:
            val: the value to be validated

        Returns:
            boolean : if value is valid against schema.

        """
        return SchemaValidatorWrapper.getValidator(APIHelper.get_schema_path(os.path.abspath(__file__))).is_valid(val)
