
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-05T11:40:10+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "fc02a1879db19e1f0666b4667dcc9f55ff0424c1",
 "version": "0.7.1.post.dev505"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
