[tool.poetry]
name = "dav-xmpp-sync"
version = "1.0.0"
description = "Synchronizes contact names from CardDav to XMPP/SMS gateways"
authors = ["Sumit Khanna <sumit@penguindreams.org>"]
license = "AGPLv3"
packages = [
  { include = "davxmppsync", from = "." }
]


[tool.poetry.scripts]
dav-xmpp-sync = 'davxmppsync.__main__:main'

[tool.poetry.dependencies]
python = "^3.10"
xmpppy = "^0.7.0"
requests = "^2.27.1"
rich = "^11.0.0"
click = "^8.0.3"
PyYAML = "^6.0"

[tool.poetry.dev-dependencies]
responses = "^0.17.0"
pytest = "^6.2.5"
pycodestyle = "^2.8.0"
flake8 = "^4.0.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
