"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _YoutubeFailureReason:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType
class _YoutubeFailureReasonEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_YoutubeFailureReason.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    NONE: _YoutubeFailureReason.ValueType  # 0
    NOT_FOUND: _YoutubeFailureReason.ValueType  # 1
    API_REJECTED: _YoutubeFailureReason.ValueType  # 2
    TRANSPORT_FAILURE: _YoutubeFailureReason.ValueType  # 3
class YoutubeFailureReason(_YoutubeFailureReason, metaclass=_YoutubeFailureReasonEnumTypeWrapper):
    pass

NONE: YoutubeFailureReason.ValueType  # 0
NOT_FOUND: YoutubeFailureReason.ValueType  # 1
API_REJECTED: YoutubeFailureReason.ValueType  # 2
TRANSPORT_FAILURE: YoutubeFailureReason.ValueType  # 3
global___YoutubeFailureReason = YoutubeFailureReason


class StateChange(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    class _State:
        ValueType = typing.NewType('ValueType', builtins.int)
        V: typing_extensions.TypeAlias = ValueType
    class _StateEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[StateChange._State.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        IDLE: StateChange._State.ValueType  # 0
        ERRORED: StateChange._State.ValueType  # 1
        SEARCHING_SPOTIFY: StateChange._State.ValueType  # 2
        SEARCHICH_SPOTIFY_DONE: StateChange._State.ValueType  # 3
        SEARCHING_YOUTUBE: StateChange._State.ValueType  # 4
        SEARCHING_YOUTUBE_DONE: StateChange._State.ValueType  # 5
        FETCHING_SPOTIFY_ANALYSIS: StateChange._State.ValueType  # 6
        FETCHING_SPOTIFY_ANALYSIS_DONE: StateChange._State.ValueType  # 7
        FETCHING_YOUTUBE_AUDIO: StateChange._State.ValueType  # 8
        FETCHING_YOUTUBE_AUDIO_DONE: StateChange._State.ValueType  # 9
        ENGINE_ANALYZING: StateChange._State.ValueType  # 10
        ENGINE_ANALYZING_DONE: StateChange._State.ValueType  # 11
        TRANSCODING: StateChange._State.ValueType  # 12
        TRANSCODING_DONE: StateChange._State.ValueType  # 13
        STREAMING_INITIALIZING: StateChange._State.ValueType  # 14
        STREAMING: StateChange._State.ValueType  # 15
        STREAMING_DONE: StateChange._State.ValueType  # 16
    class State(_State, metaclass=_StateEnumTypeWrapper):
        pass

    IDLE: StateChange.State.ValueType  # 0
    ERRORED: StateChange.State.ValueType  # 1
    SEARCHING_SPOTIFY: StateChange.State.ValueType  # 2
    SEARCHICH_SPOTIFY_DONE: StateChange.State.ValueType  # 3
    SEARCHING_YOUTUBE: StateChange.State.ValueType  # 4
    SEARCHING_YOUTUBE_DONE: StateChange.State.ValueType  # 5
    FETCHING_SPOTIFY_ANALYSIS: StateChange.State.ValueType  # 6
    FETCHING_SPOTIFY_ANALYSIS_DONE: StateChange.State.ValueType  # 7
    FETCHING_YOUTUBE_AUDIO: StateChange.State.ValueType  # 8
    FETCHING_YOUTUBE_AUDIO_DONE: StateChange.State.ValueType  # 9
    ENGINE_ANALYZING: StateChange.State.ValueType  # 10
    ENGINE_ANALYZING_DONE: StateChange.State.ValueType  # 11
    TRANSCODING: StateChange.State.ValueType  # 12
    TRANSCODING_DONE: StateChange.State.ValueType  # 13
    STREAMING_INITIALIZING: StateChange.State.ValueType  # 14
    STREAMING: StateChange.State.ValueType  # 15
    STREAMING_DONE: StateChange.State.ValueType  # 16

    OLD_STATE_FIELD_NUMBER: builtins.int
    NEW_STATE_FIELD_NUMBER: builtins.int
    MIN_PROGRESS_FIELD_NUMBER: builtins.int
    MAX_PROGRESS_FIELD_NUMBER: builtins.int
    NEW_PROGRESS_FIELD_NUMBER: builtins.int
    ERROR_MESSAGE_FIELD_NUMBER: builtins.int
    old_state: global___StateChange.State.ValueType
    new_state: global___StateChange.State.ValueType
    min_progress: builtins.int
    max_progress: builtins.int
    new_progress: builtins.int
    error_message: typing.Text
    def __init__(self,
        *,
        old_state: global___StateChange.State.ValueType = ...,
        new_state: global___StateChange.State.ValueType = ...,
        min_progress: builtins.int = ...,
        max_progress: builtins.int = ...,
        new_progress: builtins.int = ...,
        error_message: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["error_message",b"error_message","max_progress",b"max_progress","min_progress",b"min_progress","new_progress",b"new_progress","new_state",b"new_state","old_state",b"old_state"]) -> None: ...
global___StateChange = StateChange

class ArbitraryAudioChunk(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    TOTAL_CHUNK_COUNT_FIELD_NUMBER: builtins.int
    CURRENT_CHUNK_INDEX_FIELD_NUMBER: builtins.int
    DATA_BYTES_FIELD_NUMBER: builtins.int
    total_chunk_count: builtins.int
    current_chunk_index: builtins.int
    data_bytes: builtins.bytes
    """limit to 3 MiB"""

    def __init__(self,
        *,
        total_chunk_count: builtins.int = ...,
        current_chunk_index: builtins.int = ...,
        data_bytes: builtins.bytes = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["current_chunk_index",b"current_chunk_index","data_bytes",b"data_bytes","total_chunk_count",b"total_chunk_count"]) -> None: ...
global___ArbitraryAudioChunk = ArbitraryAudioChunk

class RIFFWAVEHeader(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    CHANNEL_COUNT_FIELD_NUMBER: builtins.int
    SAMPLE_RATE_FIELD_NUMBER: builtins.int
    SAMPLE_SIZE_FIELD_NUMBER: builtins.int
    SAMPLE_COUNT_FIELD_NUMBER: builtins.int
    channel_count: builtins.int
    sample_rate: builtins.int
    sample_size: builtins.int
    sample_count: builtins.int
    def __init__(self,
        *,
        channel_count: builtins.int = ...,
        sample_rate: builtins.int = ...,
        sample_size: builtins.int = ...,
        sample_count: builtins.int = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["channel_count",b"channel_count","sample_count",b"sample_count","sample_rate",b"sample_rate","sample_size",b"sample_size"]) -> None: ...
global___RIFFWAVEHeader = RIFFWAVEHeader

class RIFFWAVEChunk(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    CHUNK_FIELD_NUMBER: builtins.int
    @property
    def chunk(self) -> global___ArbitraryAudioChunk: ...
    def __init__(self,
        *,
        chunk: typing.Optional[global___ArbitraryAudioChunk] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["chunk",b"chunk"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["chunk",b"chunk"]) -> None: ...
global___RIFFWAVEChunk = RIFFWAVEChunk

class OpusHeader(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    IS_DISCORD_READY_FIELD_NUMBER: builtins.int
    is_discord_ready: builtins.bool
    def __init__(self,
        *,
        is_discord_ready: builtins.bool = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["is_discord_ready",b"is_discord_ready"]) -> None: ...
global___OpusHeader = OpusHeader

class OpusChunk(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    CHUNK_FIELD_NUMBER: builtins.int
    @property
    def chunk(self) -> global___ArbitraryAudioChunk: ...
    def __init__(self,
        *,
        chunk: typing.Optional[global___ArbitraryAudioChunk] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["chunk",b"chunk"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["chunk",b"chunk"]) -> None: ...
global___OpusChunk = OpusChunk

class DiscordRadioStreamChunk(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    HEADER_FIELD_NUMBER: builtins.int
    CHUNK_FIELD_NUMBER: builtins.int
    STATE_CHANGE_FIELD_NUMBER: builtins.int
    @property
    def header(self) -> global___OpusHeader: ...
    @property
    def chunk(self) -> global___OpusChunk: ...
    @property
    def state_change(self) -> global___StateChange: ...
    def __init__(self,
        *,
        header: typing.Optional[global___OpusHeader] = ...,
        chunk: typing.Optional[global___OpusChunk] = ...,
        state_change: typing.Optional[global___StateChange] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["chunk",b"chunk","header",b"header","state_change",b"state_change"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["chunk",b"chunk","header",b"header","state_change",b"state_change"]) -> None: ...
global___DiscordRadioStreamChunk = DiscordRadioStreamChunk

class StreamingParameters(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    THRESHOLD_FIELD_NUMBER: builtins.int
    BOUND_LOWER_FIELD_NUMBER: builtins.int
    BOUND_HIGHER_FIELD_NUMBER: builtins.int
    RAMP_UP_SPEED_FIELD_NUMBER: builtins.int
    ONLY_REVERSE_FIELD_NUMBER: builtins.int
    ONLY_LONG_FIELD_NUMBER: builtins.int
    EXTERNAL_AUDIO_FIELD_NUMBER: builtins.int
    threshold: builtins.float
    bound_lower: builtins.float
    bound_higher: builtins.float
    ramp_up_speed: builtins.float
    only_reverse: builtins.bool
    only_long: builtins.bool
    external_audio: typing.Text
    def __init__(self,
        *,
        threshold: builtins.float = ...,
        bound_lower: builtins.float = ...,
        bound_higher: builtins.float = ...,
        ramp_up_speed: builtins.float = ...,
        only_reverse: builtins.bool = ...,
        only_long: builtins.bool = ...,
        external_audio: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["bound_higher",b"bound_higher","bound_lower",b"bound_lower","external_audio",b"external_audio","only_long",b"only_long","only_reverse",b"only_reverse","ramp_up_speed",b"ramp_up_speed","threshold",b"threshold"]) -> None: ...
global___StreamingParameters = StreamingParameters

class DiscordRadioStreamRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ID_FIELD_NUMBER: builtins.int
    PARAMETERS_FIELD_NUMBER: builtins.int
    id: typing.Text
    @property
    def parameters(self) -> global___StreamingParameters: ...
    def __init__(self,
        *,
        id: typing.Text = ...,
        parameters: typing.Optional[global___StreamingParameters] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["parameters",b"parameters"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["id",b"id","parameters",b"parameters"]) -> None: ...
global___DiscordRadioStreamRequest = DiscordRadioStreamRequest

class DiscordRadioStreamResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    CHUNKS_FIELD_NUMBER: builtins.int
    @property
    def chunks(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___DiscordRadioStreamChunk]: ...
    def __init__(self,
        *,
        chunks: typing.Optional[typing.Iterable[global___DiscordRadioStreamChunk]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["chunks",b"chunks"]) -> None: ...
global___DiscordRadioStreamResponse = DiscordRadioStreamResponse

class YoutubeUrlForSpotifyIDRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ID_FIELD_NUMBER: builtins.int
    id: typing.Text
    def __init__(self,
        *,
        id: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["id",b"id"]) -> None: ...
global___YoutubeUrlForSpotifyIDRequest = YoutubeUrlForSpotifyIDRequest

class YoutubeUrlForSpotifyIDResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    URL_FIELD_NUMBER: builtins.int
    url: typing.Text
    def __init__(self,
        *,
        url: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["url",b"url"]) -> None: ...
global___YoutubeUrlForSpotifyIDResponse = YoutubeUrlForSpotifyIDResponse

class YoutubeAudioDataRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    URL_FIELD_NUMBER: builtins.int
    url: typing.Text
    def __init__(self,
        *,
        url: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["url",b"url"]) -> None: ...
global___YoutubeAudioDataRequest = YoutubeAudioDataRequest

class YoutubeAudioDataResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    CHUNK_FIELD_NUMBER: builtins.int
    ERROR_FIELD_NUMBER: builtins.int
    @property
    def chunk(self) -> global___ArbitraryAudioChunk: ...
    error: global___YoutubeFailureReason.ValueType
    def __init__(self,
        *,
        chunk: typing.Optional[global___ArbitraryAudioChunk] = ...,
        error: global___YoutubeFailureReason.ValueType = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["chunk",b"chunk"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["chunk",b"chunk","error",b"error"]) -> None: ...
global___YoutubeAudioDataResponse = YoutubeAudioDataResponse
