# Generated by Django 3.2.7 on 2022-04-03 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0008_auto_20211215_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='informations',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='role',
            name='informations',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
