---
Equities:
  - SHOP
  - AAPL
  - AC.TO
  - ZQQ.TO
  - SHOP.TO
  - TMD.TO
  - KEY.TO

# https://etfdb.com/etfs/investment-style/dividend-etfs/#etfs__dividends&sort_name=dividend_yield&sort_order=desc&page=1
# https://www.etf.com/etfanalytics/etf-finder/
ETFs:
  # US
  - XITK
  - XSD
  - SMH
  - XBI
  - XRT
  - FDIS
  - SIVR
  - VCR
  - FDN
  - JKK
  - QQQ
  - VGT
  - HDEF
  - CIBR
  - GQRE
  - FTC
  - VLUE
  - SPY
  - IWM
  # US Corp bonds
  - HYG
  - LQD
  # North America
  - EWC
  - FXC
  - PXI
  - RPV
  - XMLV
  # Asia Pacific
  - VPL
  - FLJP
  - EWY
  # Developed Markets
  - SCHF

exchanges_to_scrape:
  - TOR
  - NCM
  - NYQ

scrape:
  tickers:
#    P2
    - MEOH
    - AAPL
    - TWTR
    - GIB
    - ASML
#    P1
#    - AMZN
#    - ATD-B.TO
#    - MTL.TO
#    - T.TO
#    - DIS
#    - ASML
#    - TSM
#    - AAPL
#    - BRK-B
#    - KMI
#    - BAM-A.TO
#    - BIP-UN.TO
#    - CNI
#    - CSU.TO
#    - X.TO
#    - MA
#    - MELI
#    - NVDA
#    - PYPL
#    - MTY.TO
#    - CPER
#    - SIVR
#    - BDRY
#    - PDBC
#    - USO
#    - UNG
#    - UGA
  interval_start: 2021-05-01
  interval_end: 2021-05-25
  interval: 5m

portfolio:
  ZQQ.TO:
    enter_price: 72.14
    sell_price: 75
    quit_price: 73.5
        
  TMD.TO:
    enter_price: 1.82
    sell_price: 1.9
    quit_price: 1.5

tbills:
  url: https://www.bankofcanada.ca/valet/observations/group/tbill_all/csv
  1year: