[tool.poetry]
name = "mainpy"
version = "1.0.0"
description = "Simplify your project's main entrypoint definition with @main"
authors = ["Joren Hammudoglu <jhammudoglu@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/jorenham/mainpy"

[tool.poetry.dependencies]
python = "^3.7"
typing_extensions = { version = "^4.1", python = "<3.10"}

[tool.poetry.dev-dependencies]
pytest = "^7.1"
pyright = "^1.1"

uvloop = "^0.16"

[tool.pyright]
include = ["mainpy"]
exclude = [".git", "dist",  "build", "**/__pycache__", "**/.pytest_cache"]
venv = ".venv"
pythonVersion = "3.7"
pythonPlatform = "Linux"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
