
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-05T11:54:21+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "927b87fdbae9a07c52c89e2b72afe6d4b66cd954",
 "version": "0.7.1.post.dev509"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
