[build-system]
requires = [ "poetry>=0.12",]
build-backend = "poetry.masonry.api"

[tool.poetry]
name = "pipen"
version = "0.2.15"
description = "A pipeline framework for python"
authors = [ "pwwang <pwwang@pwwang.com>",]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/pwwang/pipen"
repository = "https://github.com/pwwang/pipen"

[tool.poetry.dependencies]
python = "^3.7.1" # align with datar/pandas
toml = "^0.10"
varname = "*"
liquidpy = "^0.7"
diot = "*"
pyparam = "*"
xqute = "*"
python-simpleconf = "*"
pandas = "1.*"
rich = "10.*"
python-slugify = "5.*"
simplug = "*"
enlighten = "1.*"
cached-property = "1.*"
more-itertools = "8.*"
pipda = "*"

[tool.poetry.dev-dependencies]
pytest = "*"
pytest-cov = "*"
datar = "*"
openpyxl = "3.*"

[tool.poetry.scripts]
pipen = "pipen.cli:main"

[tool.pytest.ini_options]
addopts = "-vv -W error::UserWarning --cov-config=.coveragerc --cov=pipen --cov-report xml:.coverage.xml --cov-report term-missing"
# addopts = "-vv -W error::UserWarning --cov-config=.coveragerc --cov-report xml:.coverage.xml --cov-report term-missing"
console_output_style = "progress"
junit_family = "xunit1"

[tool.mypy]
ignore_missing_imports = true
allow_redefinition = true
disable_error_code = ["attr-defined", "no-redef"]
show_error_codes = true
strict_optional = false

[tool.black]
line-length = 79
target-version = ['py37', 'py38', 'py39']
include = '\.pyi?$'
