
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-04T16:13:42+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "8b5f4575ed801e16cf8124bf8bbbc7e4ade394e8",
 "version": "v1.1.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
