[tool.poetry]
name = "backlog-schema"
version = "0.1.1"
description = "backlog.com の pydantic model"
authors = ["Niten Nashiki <n.nashiki.work@gmail.com>"]
readme = "README.md"
homepage = "https://github.com/nnashiki/backlog-schema"
repository = "https://github.com/nnashiki/backlog-schema"

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
datamodel-code-generator = "^0.11.20"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
