name: CI

on: [push, pull_request]

jobs:
  test:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    defaults:
      run:
        shell: bash -l {0}  # a login shell is required for conda activation
    steps:
      - uses: actions/checkout@v2
      - name: Create Conda environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: conda-linux-64.lock
          use-only-tar-bz2: true
      - name: Install test dependencies
        run: conda install -c conda-forge pytest pip
      - name: Install IgDiscover
        run: pip install --no-deps .
      - name: Enable cache
        run: "echo 'use_cache: true' > $HOME/.config/igdiscover.conf"
      - name: Download test data
        run: |
          wget -nv https://bitbucket.org/igdiscover/testdata/downloads/igdiscover-testdata-0.7.tar.gz
          tar xvf igdiscover-testdata-0.7.tar.gz
          ln -s igdiscover-testdata testdata
      - name: Run tests
        run: pytest

  deploy:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    needs: [test]
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0  # required for setuptools_scm
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Build sdist and wheel
      run: |
        python -m pip install build
        python -m build
        ls -l dist/
    - name: Publish dev release to test PyPI
      if: contains(github.ref, '.dev')
      uses: pypa/gh-action-pypi-publish@v1.4.2
      with:
        user: __token__
        password: ${{ secrets.test_pypi_password }}
        repository_url: https://test.pypi.org/legacy/
    - name: Publish to PyPI
      if: "!contains(github.ref, '.dev')"
      uses: pypa/gh-action-pypi-publish@v1.4.2
      with:
        user: __token__
        password: ${{ secrets.pypi_password }}
