
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-06T06:54:15-0700",
 "dirty": true,
 "error": null,
 "full-revisionid": "f5515a00aaab0938795da010d4c4e7725b1d6deb",
 "version": "v1.2.0a4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
