[tool.poetry]
authors = ["Shane Anderson <shane@reactivate.cx>"]
description = "Simple & fast multi-threaded S3 download tool."
keywords = ["aws", "s3"]
license = "MIT"
name = "s3fetch"
readme = "README.md"
repository = "https://github.com/rxvt/s3fetch"
version = "1.1.2"

[tool.poetry.dependencies]
boto3 = "^1.15.18"
click = "^8.0.0"
python = "^3.7"
urllib3 = "1.26.8"

[tool.poetry.dev-dependencies]
black = "^22.3.0"
moto = "^3.0.2"
nox = "^2020.8.22"
nox-poetry = "^0.5.0"
pytest = "^5.2"
pytest-cov = "^2.10.1"
pytest-mock = "^3.3.1"
mypy = "^0.931"
flake8 = "^4.0.1"

[tool.poetry.scripts]
s3fetch = 's3fetch:cmd'

[build-system]
build-backend = "poetry.masonry.api"
requires = ["poetry>=0.12"]
