
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-07T20:36:05-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "3dafaad8545c745a0fe2688d2b40cc873ef85fc2",
 "version": "0.15.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
