
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-04T12:12:03+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "f4c19efc3d06990bd83e4cf73611eb14c27be65d",
 "version": "1.0.8rc8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
