import numpy as np
from typing import Any

def linspace(start, end, count): ...
def meshcorners(corners, grid): ...
def cutpatch(data: np.ndarray, corners: np.ndarray, grid: tuple, fill: Any | None = ...): ...
