XXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXX

XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXX XX XXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXX XXXXXXXXXXX XX
XXXXXXX XXXX XXX XXX XXXXXX X XXXXXXXXX XXXX XXX XXXXXXX XX XXXX XXX XXXXX XXXX XX XXXXXXXXXXX XXX XXXXX XXXX XXXXXXXX
XXXXXXXXXX XXXXX XXXXXX XXX XXXXX XXXXXXX XXX XXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXX XXXXX XX XX XXXXXXX XXXX XXXXX XXX
XXXXX XXXX XXXX XXX XXXX XXX XXXXXX XXXX XXXXXXX XXXX XX XXXX XXX XXX XXX XXXXXXXX XXXXXX XXXX XXX XXXXXXXX XXX XXX XX
XXXXXX XXXXX XXXXXXXX XXXXX XXXXXXXXX XXXXXXXXXX XXXX XXXXXX

XX XXXXXXXXX

   XXXX XXXXXX XX XXX XXXX XXXXXXXX XXX XXX XX XXX XXX XXXXX XXXX XXXXXXXX XXXXXXXXXXXXX XXX XXXXX XXXXXXX XX XXX XX
   XXXXXX XXXX XXXX XXX XXXX XXXXXXXX XXX XXXXXXXX

XXXXXXXXX XXXX XXXXX
XXXXXXXXXXXXXXXXXXXX
XX XXXXXXXXX
   XXXXXXXXXX X

   XXXXXXXXX
   XXXX
   XXXXXXXX
   XXXXX
   XXXXXXXX
   XXXXXXXXXX
   XXXXXXXXX

XXXXXXXXX XXXXX XXXXXXXXX XXXXXXXX

XXXXX XXXXXXXXXX
XXXXXXXXXXXXXXXX
XXX XXXXXXXXXX XXXXXXX XXX XXXXXXXX XXXXXX XXX XXXXXXXXX XX XXX XXXXX XXX XXXXXXXXXX XXXXXXXXXXXXXX XXXXXX XX XXXXX
XXXXXXXXXXX XXXXXX XXXXX XXXXXX XXX XX XXXXXXX XX XXXX XXXXXXXXX XX XXXXXXXXXXX XX XXX X XXXXXXXX XX XXXX XXXXX
XXXXXXXX XXX XXXXXXXX XXXXX XXX XXXX XXXXXX XXXX XXXXX XXXXX XXXXXXXXXX XXX XXX XXXXX XXX X XXXX XXXXXXXX XXXXXXXXXX
XXX XXXX XXXXXX

XXXX XXXXXXXXXX XXXX XX XXXX XXXXXXX XX XXXX XXXXXXX XXX XXXX XXXX XX XXXXXX XX XXXXXX XXXX XXXXX XXXXXX XX XXXX XXXX
XXXXXX XXXXXXXXXX XX XXX XX XXX XXXXXXX XXXX XX XXXX XXXXXXXX XXX XXXX XXXX XX XXXX XX XXXXXX XXX XX XXXXXXX XXXXXX
XXXX XXXX XXXX XXXXXXXX XXX XXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXX X XXXX XX XX XXXXXXXX XXXXXXXX XXXXXXXXXX XXX XXXXXXX

XXXXXXX XXX XXXXXX
XXXXXXXXXXXXXXXXXX

X XXXXXXXXXXXXXXX
X XXXXXXXXXXXXXXX
X XXXXXXXXXXXXX