
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-06T13:33:38+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "e78c32e8b11e3373ca8a297423d94991c0a3b83d",
 "version": "0.4.139"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
