
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-05T15:51:45-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "46bcbf62531619ac8e2164d25b76e2fe8a686051",
 "version": "1.5.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
