# Generated by Django 4.0.3 on 2022-04-01 01:04

import django.db.models.deletion
from django.db import migrations, models

import django_countries.fields

import unicef_business_areas.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='code')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='name')),
            ],
            bases=(models.Model, unicef_business_areas.models.TimeStampedModel),
        ),
        migrations.CreateModel(
            name='BusinessArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='code')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='name')),
                ('long_name', models.CharField(max_length=150, verbose_name='long name')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unicef_business_areas.region')),
            ],
            options={
                'swappable': 'BUSINESSAREA_MODEL',
            },
            bases=(models.Model, unicef_business_areas.models.TimeStampedModel),
        ),
    ]
