
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-06T19:16:24+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "04e61e7fa4396d55da843005bd78db3dca348183",
 "version": "v11.7.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
