[tool.poetry]
name = "requests-http-message-signatures"
version = "0.3.0-dev1"
description = ""
authors = ["Funkwhale Collective <maintainers@funkwhale.audio>"]

[tool.poetry.dependencies]
python = "^3.7"
cryptography = ">=1.8.2"
requests = "^2"

[tool.poetry.dev-dependencies]
Sphinx = "^4.5.0"
coverage = "^6.3.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
