
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-01T17:58:34+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "51093d3a64e304c5c35f4fc203d561f3d21df99c",
 "version": "1.38.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
