[tool.poetry]
name = "auto_notion_py"
version = "0.1.4"
description = "Notion automation package"
authors = ["Piotr Styczyński <pstyczynski@sumologic.com>"]
readme = "README.md"

[tool.poetry.scripts]
publish = 'publish:publish'

[tool.poetry.dependencies]
python = "^3.8"
pandas = "^1.3.5"
notion-client = "^0.8.0"
moment = "^0.12.1"
jupyter = "^1.0.0"
githubpy = "^1.1.0"
PyGithub = "^1.55"
aiomultiprocess = "^0.9.0"
pyzotero = "^1.5.1"
mistletoe = "^0.8.2"
requests = "^2.27.1"
commonmark = "^0.9.1"
dictdiffer = "^0.9.0"
python-slugify = "^6.1.1"
cached-property = "^1.5.2"
tzlocal = "^4.2"
bs4 = "^0.0.1"
plotly = "^5.6.0"
matplotlib = "^3.5.1"
chart-studio = "^1.1.0"

[tool.poetry.dev-dependencies]
pytest = "^6.2.1"
flakehell = "0.9.0"
flake8 = "3.8.3"
pytest-xdist = "^2.2.0"
isort = "^5.7.0"
black = "^20.8b1"
pydoc-markdown = "^3.9.0"
s3pypi = "^0.11.0"
poetry-publish = "^0.4.1"
bump2version = "^1.0.1"

[tool.black]
line-length = 79
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.flakehell]
exclude = ["README.rst", "README.md", "venv"]
format = "colored"
max_line_length = 120
show_source = true
whitelist = "../../allowlist.txt"

[tool.flakehell.plugins]
flake8-bandit = ["+*", "-S322"]
flake8-bugbear = ["+*"]
flake8-builtins = ["+*"]
flake8-comprehensions = ["+*"]
flake8-darglint = ["+*"]
flake8-docstrings = ["+*"]
flake8-eradicate = ["+*"]
flake8-isort = ["+*"]
flake8-mutable = ["+*"]
flake8-pytest-style = ["+*"]
flake8-spellcheck = ["+*"]
mccabe = ["+*"]
pep8-naming = ["+*"]
pycodestyle = ["+*", "-E203", "-W503"]
pyflakes = ["+*", "-E203"]
pylint = ["+*", "-E203"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

