[tool.poetry.plugins."poetry.plugin"]
poetry-version-plugin = "poetry_version_plugin.plugin:VersionPlugin"

[tool.poetry]
name = "my-example-project"
version = "0.1.2"
description = ""
authors = ["Lingling <you@example.com>"]

packages = [
    { include = "my-example-project" },
    { include = "my-example-project/**/*.py" },
]

[tool.poetry.dependencies]
python = "^3.8"
poetry-version-plugin = "^0.1.3"

[tool.poetry.dev-dependencies]
pytest = "^6.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry-version-plugin]
source = "git-tag"
