[project]
name = "dpvisu"
version = "0.7.5"
description = "A bodge disguised as a tool that generates call-graphs when let loose on a datapack."
authors = [
    { name = "UncleThaodan", email = "unclethaodan@gmail.com" },
]
license-expression = "GPL-3.0"
dependencies = [
    "diagrams>=0.21.1",
]
requires-python = ">=3.9.5"
readme = "README.md"
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
]

[project.scripts]
dpvisu = "main:run"

[project.urls]
Repository = "https://gitlab.com/UncleThaodan/datapack_visualizer"

[tool.pdm]
package-dir = "src"
includes = [
    "src",
]

[build-system]
requires = [
    "pdm-pep517>=0.12.0",
]
build-backend = "pdm.pep517.api"
