[tool.poetry]
authors = ["Denis Rosset <physics@denisrosset.com>"]
description = "Python adaptive plotting library"
license = "MIT"
name = "vegoia"
version = "0.1.0"

[tool.poetry.dependencies]
matplotlib = "^3.0"
numpy = "^1.21"
python = ">=3.7,<3.11"
scipy = "^1.7.0"
typing-extensions = "^4.1.1"

beartype = {version = "^0.10.4", optional = true}
myst-nb = {version = "^0.13.2", optional = true}
sphinx = {version = "4.3.2", optional = true}
sphinx-autodoc-typehints = {version = "^1.17.0", optional = true}
sphinx-book-theme = {version = "^0.2.0", optional = true}

[tool.poetry.extras]
beartype = ["beartype"]
docs = [
  "myst-nb",
  "sphinx",
  "sphinx-autodoc-typehints",
  "sphinx-book-theme",
]

[tool.poetry.dev-dependencies]
black = "^22.1.0"
commitizen = "^2.21.2"
doc8 = "^0.10.1"
esbonio = "^0.10.2"
isort = "^5.10.1"
mypy = "0.941"
pytest = "^7.0.1"
pytest-cov = "^3.0.0"
rstcheck = "^3.3.1"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]

[tool.mypy]
python_version = "3.7"

files = [
  "src/vegoia",
  "tests",
]
mypy_path = "$MYPY_CONFIG_FILE_DIR/src"

check_untyped_defs = true
disallow_any_generics = true
disallow_incomplete_defs = true
disallow_subclassing_any = true
disallow_untyped_calls = true
disallow_untyped_decorators = true
disallow_untyped_defs = true
no_implicit_optional = true
show_column_numbers = true
show_error_codes = true
show_error_context = true
show_none_errors = true
strict_equality = true
strict_optional = true
warn_redundant_casts = true
warn_return_any = true

[tool.pytest.ini_options]
addopts = [
  "--tb=short",
  "--doctest-modules",
  "--cov=configpile",
  "--cov=tests",
  "--cov-report=term",
  "--cov-report=xml",
]

doctest_optionflags = ['NORMALIZE_WHITESPACE', 'IGNORE_EXCEPTION_DETAIL', 'ELLIPSIS']

testpaths = [
  "src/vegoia",
  "tests",
]

[tool.black]
line-length = 99
target_version = ['py37']

[tool.doc8]
max-line-length = 99

[tool.isort]
line_length = 99
profile = "black"
py_version = 37

[tool.commitizen]
annotated_tag = true
name = "cz_conventional_commits"
style = [
  ["qmark", "fg:#ff9d00 bold"],
  ["question", "bold"],
  ["answer", "fg:#ff9d00 bold"],
  ["pointer", "fg:#ff9d00 bold"],
  ["highlighted", "fg:#ff9d00 bold"],
  ["selected", "fg:#cc5454"],
  ["separator", "fg:#cc5454"],
  ["instruction", ""],
  ["text", ""],
  ["disabled", "fg:#858585 italic"],
]
tag_format = "v$major.$minor.$patch$prerelease"
update_changelog_on_bump = true
version = "8.0.0"
version_files = [
  "src/configpile/__init__.py:version",
  "pyproject.toml:version",
]
