[tool.poetry]
name = "cuda_hybrid"
version = "0.1.0"
description = "Runs ABM/FCM hybrid models on CUDA cores to drastically reduce runtime."
authors = ["Kareem Ghumrawi <kghumrawi@gmail.com>"]
license = "GPL-3.0-only"
readme = "README.md"
repository = "https://gitlab.csi.miamioh.edu/620_final/cse620c_finalproject/-/tree/add-docs"
documentation = "https://gitlab.csi.miamioh.edu/620_final/cse620c_finalproject/-/blob/add-docs/docs/build/html/index.html"
keywords = [
	"Hybrid Models",
	"CUDA",
	"ABM",
	"FCM"
]

[tool.poetry.dependencies]
python = "^3.7"
networkx = "\b2.6.3"
numba = "\b0.48.0"
numpy = "\b1.20.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
