name: Documentation

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10.0]
      fail-fast: false

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/cache@v2
        id: cache
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ runner.os }}-python-${{ env.pythonLocation }}-${{ hashFiles('pyproject.toml') }}-test
      - name: Install Flit
        if: steps.cache.outputs.cache-hit != 'true'
        run: pip install flit
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: flit install --symlink
      - name: Build
        run: mkdocs build
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: docs
          folder: ./site
          message: "💫 Build Documentation"