[tool.poetry]
name = "yapper"
version = "0.2.0b1"
description = "Simple python parser converting docstrings to .astro files for the Astro static site generator."
authors = ["Gareth Simons <garethsimons@me.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
docstring-parser = "^0.13"
PyYAML = "^6.0"
dominate = "^2.6.0"
python-slugify = "^6.1.1"
Markdown = "^3.3.6"

[tool.poetry.dev-dependencies]
pytest = "^7.1.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
