#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['physiocurve',
 'physiocurve.common',
 'physiocurve.ecg',
 'physiocurve.flow',
 'physiocurve.ppg',
 'physiocurve.pressure',
 'physiocurve.pressure.reference']

package_data = \
{'': ['*']}

install_requires = \
['numpy>=1.16.4',
 'pandas>=1.0',
 'numba>=0.46',
 'scipy>=1.2.0',
 'py-ecg-detectors>=1.0.2']

setup(name='physiocurve',
      version='2021.6.10',
      description='Library to analyze physiologic data curves.',
      author='Jona JOACHIM',
      author_email='jona@joachim.cc',
      url='https://framagit.org/jaj/physiocurve',
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      python_requires='>=3.8',
     )
