
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-01T17:07:14+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "67ec9376d0f94c3c3b741bdb4ed9437edd628574",
 "version": "0.4.126"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
