[tool.poetry]
name = "ntfsdump"
version = "2.3.4"
description = "A tool for extract any files from an NTFS volume on an image file."
authors = ["sumeshi <sum3sh1@protonmail.com>"]
license = "LGPLv3+"
readme = "README.md"

repository = "https://github.com/sumeshi/ntfsdump"
homepage = "https://github.com/sumeshi/ntfsdump"

keywords = ['Windows']

[tool.poetry.scripts]
ntfsdump = 'ntfsdump.views.NtfsDumpView:entry_point'

[tool.poetry.dependencies]
python = "^3.9"
pytsk3 = "^20211111"
libewf-python = "^20201230"

[tool.poetry.dev-dependencies]
black = "^22.1.0"
mypy = "^0.931"
flake8 = "^4.0.1"
poetry = "^1.1.13"
pytest = "^7.0.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
