
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-05T22:25:06+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "58593de79059d45ff0947c91c52d1694b5319e9b",
 "version": "0.4.137"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
