
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-04T14:24:22+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "26106087bf12aa41472a8dfd7a29956693215fd7",
 "version": "2.0.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
