
# This file was generated by 'versioneer.py' (0.15+dev) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "c5b095a8b905d759c84acab5e8a65ed3170d124c",
 "version": "1.8.0rc4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
