"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class ListGuildsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    def __init__(self,
        ) -> None: ...
global___ListGuildsRequest = ListGuildsRequest

class Guild(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    NAME_FIELD_NUMBER: builtins.int
    ID_FIELD_NUMBER: builtins.int
    name: typing.Text
    id: typing.Text
    def __init__(self,
        *,
        name: typing.Text = ...,
        id: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["id",b"id","name",b"name"]) -> None: ...
global___Guild = Guild

class ListGuildsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    GUILDS_FIELD_NUMBER: builtins.int
    @property
    def guilds(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Guild]: ...
    def __init__(self,
        *,
        guilds: typing.Optional[typing.Iterable[global___Guild]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["guilds",b"guilds"]) -> None: ...
global___ListGuildsResponse = ListGuildsResponse

class ListChannelsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    GUILD_ID_FIELD_NUMBER: builtins.int
    guild_id: typing.Text
    def __init__(self,
        *,
        guild_id: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["guild_id",b"guild_id"]) -> None: ...
global___ListChannelsRequest = ListChannelsRequest

class Channel(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    class _ChannelType:
        ValueType = typing.NewType('ValueType', builtins.int)
        V: typing_extensions.TypeAlias = ValueType
    class _ChannelTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[Channel._ChannelType.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        TEXT: Channel._ChannelType.ValueType  # 0
        VOICE: Channel._ChannelType.ValueType  # 1
        CATEGORY: Channel._ChannelType.ValueType  # 2
        STAGE: Channel._ChannelType.ValueType  # 3
        FUTURE: Channel._ChannelType.ValueType  # 4
    class ChannelType(_ChannelType, metaclass=_ChannelTypeEnumTypeWrapper):
        pass

    TEXT: Channel.ChannelType.ValueType  # 0
    VOICE: Channel.ChannelType.ValueType  # 1
    CATEGORY: Channel.ChannelType.ValueType  # 2
    STAGE: Channel.ChannelType.ValueType  # 3
    FUTURE: Channel.ChannelType.ValueType  # 4

    NAME_FIELD_NUMBER: builtins.int
    ID_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    name: typing.Text
    id: typing.Text
    type: global___Channel.ChannelType.ValueType
    def __init__(self,
        *,
        name: typing.Text = ...,
        id: typing.Text = ...,
        type: global___Channel.ChannelType.ValueType = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["id",b"id","name",b"name","type",b"type"]) -> None: ...
global___Channel = Channel

class ListChannelsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    CHANNELS_FIELD_NUMBER: builtins.int
    @property
    def channels(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Channel]: ...
    def __init__(self,
        *,
        channels: typing.Optional[typing.Iterable[global___Channel]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["channels",b"channels"]) -> None: ...
global___ListChannelsResponse = ListChannelsResponse

class ListVoicesRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    def __init__(self,
        ) -> None: ...
global___ListVoicesRequest = ListVoicesRequest

class Voice(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    LANGUAGE_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    ID_FIELD_NUMBER: builtins.int
    language: typing.Text
    name: typing.Text
    id: typing.Text
    def __init__(self,
        *,
        language: typing.Text = ...,
        name: typing.Text = ...,
        id: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["id",b"id","language",b"language","name",b"name"]) -> None: ...
global___Voice = Voice

class ListVoicesResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    VOICES_FIELD_NUMBER: builtins.int
    @property
    def voices(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Voice]: ...
    def __init__(self,
        *,
        voices: typing.Optional[typing.Iterable[global___Voice]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["voices",b"voices"]) -> None: ...
global___ListVoicesResponse = ListVoicesResponse

class ListMembersRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    GUILD_ID_FIELD_NUMBER: builtins.int
    guild_id: typing.Text
    def __init__(self,
        *,
        guild_id: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["guild_id",b"guild_id"]) -> None: ...
global___ListMembersRequest = ListMembersRequest

class Member(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ID_FIELD_NUMBER: builtins.int
    USERNAME_FIELD_NUMBER: builtins.int
    NICKNAME_FIELD_NUMBER: builtins.int
    DISCRIMINATOR_FIELD_NUMBER: builtins.int
    IS_IN_VOICE_CHANNEL_FIELD_NUMBER: builtins.int
    ACTIVE_VOICE_CHANNEL_ID_FIELD_NUMBER: builtins.int
    ACTIVE_VOICE_GUILD_ID_FIELD_NUMBER: builtins.int
    id: typing.Text
    username: typing.Text
    nickname: typing.Text
    discriminator: builtins.int
    is_in_voice_channel: builtins.bool
    active_voice_channel_id: typing.Text
    active_voice_guild_id: typing.Text
    def __init__(self,
        *,
        id: typing.Text = ...,
        username: typing.Text = ...,
        nickname: typing.Text = ...,
        discriminator: builtins.int = ...,
        is_in_voice_channel: builtins.bool = ...,
        active_voice_channel_id: typing.Text = ...,
        active_voice_guild_id: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["active_voice_channel_id",b"active_voice_channel_id","active_voice_guild_id",b"active_voice_guild_id","discriminator",b"discriminator","id",b"id","is_in_voice_channel",b"is_in_voice_channel","nickname",b"nickname","username",b"username"]) -> None: ...
global___Member = Member

class ListMembersResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    MEMBERS_FIELD_NUMBER: builtins.int
    @property
    def members(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Member]: ...
    def __init__(self,
        *,
        members: typing.Optional[typing.Iterable[global___Member]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["members",b"members"]) -> None: ...
global___ListMembersResponse = ListMembersResponse

class SayInChannelRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    CHANNEL_ID_FIELD_NUMBER: builtins.int
    VOICE_ID_FIELD_NUMBER: builtins.int
    TEXT_FIELD_NUMBER: builtins.int
    channel_id: typing.Text
    voice_id: typing.Text
    text: typing.Text
    def __init__(self,
        *,
        channel_id: typing.Text = ...,
        voice_id: typing.Text = ...,
        text: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["channel_id",b"channel_id","text",b"text","voice_id",b"voice_id"]) -> None: ...
global___SayInChannelRequest = SayInChannelRequest

class SayInChannelResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    SUCCESS_FIELD_NUMBER: builtins.int
    success: builtins.bool
    def __init__(self,
        *,
        success: builtins.bool = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["success",b"success"]) -> None: ...
global___SayInChannelResponse = SayInChannelResponse
