
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-01T13:39:37-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "1c4b09c7147ac9623bb142c3a2b523b050dac1d7",
 "version": "4.9.35"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
