[package]
name = "python"
version = "0.4.0"
edition = "2018"

[dependencies]
erdos = { path = "local_dependencies/erdos" }
pyo3 = { version = "0.16.2", features = ["extension-module"] }
tracing = "0.1.29"

[lib]
name = "erdos_python"
crate-type = ["cdylib"]

[package.metadata.maturin]
name = "erdos.internal"
