
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-07T14:41:42+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "0082c85fcec3e60f3bbcf4ce3ba9ae58a69f3472",
 "version": "2643"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
