[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "ur_py_ctl"
version = "0.1.0"
description = "Python wrapper around URScript (for Universal Robotics robots)."
authors = ["Anton Tetov <anton.johansson@control.lth.se>"]
repository = "https://gitlab.control.lth.se/robotlab/ur_py_ctl"

[tool.poetry.dependencies]
python = ">=3.9,<3.12"

[tool.poetry.dev-dependencies]
flake8 = "^4.0.1"
mypy = "^0.931"
black = "^21.12b0"
pre-commit = "^2.17.0"
reorder-python-imports = "^3.0.1"
pytest = "^7.1.1"

[tool.isort]
profile = "black"
