[build-system]
requires = [
    "setuptools>=42",
    "setuptools_scm[toml]>=3.4",
    "wheel",
]
build-backend = "setuptools.build_meta"

[tool.coverage.run]
omit = [
    "*/_version.py",
]

[tool.coverage.paths]
source = [
    "igwn_auth_utils/",
    "/usr/lib/python*/*-packages/igwn_auth_utils/",
    "/usr/local/lib/python*/*-packages/igwn_auth_utils/",
]

[tool.setuptools_scm]
write_to = "igwn_auth_utils/_version.py"

[tool.pytest.ini_options]
addopts = "-r a --color=yes"
filterwarnings = [
	"error",
	# https://github.com/pyreadline/pyreadline/issues/65
	"ignore:Using or importing the ABCs::pyreadline",
]
