[tool.poetry]
name = "pyconsmenu"
version = "1.0.1"
description = "Create menu in terminal, guide = youtube.com/watch?v=haSVq3-v1Jk"
authors = ["LON112 <blonylow@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
