[tool.black]
line-length = 120
preview = true

[tool.isort]
profile = "black"
known_first_party = "sentinelhub"
known_absolute = "s2cloudless"
sections = ["FUTURE","STDLIB","THIRDPARTY","FIRSTPARTY","ABSOLUTE","LOCALFOLDER"]
line_length = 120

[tool.pytest.ini_options]
markers = [
    "sh_integration: marks integration tests with Sentinel Hub service"
]

[tool.coverage.run]
source = [
    "s2cloudless"
]

[tool.coverage.report]
omit = [
    "models/*"
]
