import os

WF_AIRTABLE_API_AUTH0_AUDIENCE = os.getenv(
    "WF_AIRTABLE_API_AUTH0_AUDIENCE", None)

WF_AIRTABLE_API_AUTH0_DOMAIN = os.getenv(
    "WF_AIRTABLE_API_AUTH0_DOMAIN", None)

WF_AIRTABLE_API_AUTH0_CLIENT_ID = os.getenv(
    "WF_AIRTABLE_API_AUTH0_CLIENT_ID", None)

WF_AIRTABLE_API_AUTH0_CLIENT_SECRET = os.getenv(
    "WF_AIRTABLE_API_AUTH0_CLIENT_SECRET", None)

WF_AIRTABLE_API_URL = os.getenv(
    "WF_AIRTABLE_API_URL", None)
