language: python
services: docker
cache: pip


matrix:
  include:
  - python: "3.7"
  - python: "3.7"
    env: mode=codestyle
  - python: "3.8"
  - python: "3.9"


before_install:
  - image="netsandbox/request-tracker:5.0"
 
install:
  - docker pull $image
  - docker run -d --name rt -p 8080:8080 -e RT_WEB_PORT=8080 $image
  - docker ps
  - pip install coveralls codecov nose
  - if [[ $mode == codestyle ]]; then pip install pycodestyle; fi

script:
  - python setup.py install
  - nosetests --with-coverage
  - if [[ $mode == codestyle ]]; then pycodestyle rt/rt.py; fi

after_success:
  - codecov
