"""
    Delphix DCT API

    Delphix DCT API  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: support@delphix.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import delphix.api.gateway
from delphix.api.gateway.model.errors import Errors
from delphix.api.gateway.model.vdb_group import VDBGroup
globals()['Errors'] = Errors
globals()['VDBGroup'] = VDBGroup
from delphix.api.gateway.model.list_vdb_groups_response import ListVDBGroupsResponse


class TestListVDBGroupsResponse(unittest.TestCase):
    """ListVDBGroupsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testListVDBGroupsResponse(self):
        """Test ListVDBGroupsResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ListVDBGroupsResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
