
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-05T13:15:47+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "2e88a0b4347a04bcf3cce9bf226ddc8eef50603a",
 "version": "0.12.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
