
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-07T15:24:42+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "f6109ec2fffeb5a50369311b13e2972850b20665",
 "version": "0.1.1.37"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
