[tool.poetry]
name = "diffql"
version = "0.2.0"
description = "Differentiable Q-learning (DiffQL) for continuous-action deep reinforcement learning"
authors = ["Jinrae Kim <kjl950403@gmail.com>"]
license = "MIT License"

[tool.poetry.dependencies]
python = ">=3.9,<3.10"
torch = ">=1.10,<1.11"
pytest = "^6.2.5"
scipy = ">=1.8,<1.9"
numpy = ">=1.22,<1.23"
cvxpy = ">=1.1,<1.2"
cvxpylayers = ">=0.1,<0.2"
flake8 = "^4.0.1"
gym = ">=0.22,<0.23"
Mosek = ">=9.3,<9.4"
PyYAML = "^6.0"
wandb = "^0.12.11"

[tool.poetry.dev-dependencies]
ipython = "^8.0.1"
matplotlib = "^3.5.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
