[tool.poetry]
name = "syn-commodore"
version = "v0.17.1"
description = "Commodore provides opinionated tenant-aware management of Kapitan inventories and templates. Commodore uses Kapitan for the heavy lifting of rendering templates and resolving a hierachical configuration structure."
readme = "README.md"
authors = ["VSHN AG <info@vshn.ch>"]
license = "BSD-3-Clause"
homepage = "https://github.com/projectsyn/commodore"
documentation = "https://syn.tools/commodore/index.html"
packages = [
    {include = "commodore"}
]
include = [
    "commodore/component-template/**/*",
    "commodore/lib/commodore.libjsonnet",
    "commodore/filters/helm_namespace.jsonnet",
]

[tool.poetry.dependencies]
python = ">=3.7, <3.11"
kapitan = "0.30.0"
click = "*"
cookiecutter = "*"
gitpython = "*"
requests = "*"
url-normalize = "*"
python-dotenv = "*"
importlib_metadata = "*"
typing-extensions = "^3.7.4"
pyxdg = "^0.27"

[tool.poetry.dev-dependencies]
tox = "*"
autopep8 = "*"
pytest = "^5.4.3"
pytest-xdist = "^1.32.0"
pytest-benchmark = "^3.2.3"
responses = "^0.16.0"
black = "^22.1.0"
pyfakefs = "^4.5.6"
pytest-cov = "^3.0.0"
pylint = "^2.13.4"

[tool.poetry.scripts]
commodore = 'commodore.cli:main'
autopep = 'tools.tools:autopep'
local_reveal = 'tools.tools:reveal'
compile = 'tools.tools:compile'

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.coverage.run]
omit = [
    "commodore/component-template/*"
]

[tool.coverage.report]
omit = [
    "commodore/component-template/*"
]
