
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-06T16:22:16-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "5a11009f7d4d73cd4d93257bfca4b66e10f65682",
 "version": "3.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
