
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-01T11:15:08-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "034b4d4c5cfad2fe3b672425eb96b826d79d9415",
 "version": "2022.04.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
