# Generated by Django 3.2.7 on 2022-04-03 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generic_groups', '0007_genericgroup_disabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericgroup',
            name='informations',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
