[tool.poetry]
name = "shazamctl"
version = "0.0.0a0"
description = "Open-source Shazam CLI"
authors = ["Alexander Pushkov <alexander@notpushk.in>"]
license = "ISC"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
