
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-01T11:57:08-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "2b885d358d06018af3eaf0b36a34d87ca15b67c5",
 "version": "0.0.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
